### ISSUE TITLE
Nvidium + Better Clouds flickering skies bug

### ISSUE THREAD

**Issue by DeadLector** [Qendolin/better-clouds#100]
## Describe the bug
When running Nvidium and Better Clouds, the clouds flickers as you walk or jump, but not when jumpin and running simultaniously.

## To Reproduce
> Steps to reproduce the behavior

1. Add Better Clouds, and Nvidium (I installed using Modrinth Launcher so it added other necessary mods by itself.
2. Open any server/create SP world
3. Walk around and you'll see for yourself.

### Expected behavior
> A clear and concise description of what you expected to happen.

I expect no flickering for the skies. They should run smoothly like in 1.20.4 (where this bug does not exist).

### Screenshots
> If applicable, add screenshots to help explain your problem.

I've added an Imgur link to a short GIF showing the flickering issues [here](https://imgur.com/UkFT7Og). If you don't trust that link you can see the full URL here: https://imgur.com/UkFT7Og

### System Environment
- GPU: Nvidia RTX 3090
- Mod Version: 1.6.0+1.20.6-b
- OS: Windows 11 Home, Version: 10.0.22631 Build 22631

*Optional - Added automatically via Modrinth Launcher*
- Other Mods: 
- - Fabric API: 0.98.0+1.20.6
- - Sodium

### Additional context
> Add any other context about the problem here.

Related to #97 and #98.

**Comment by MrAut0** [comment]
I figured out that the bug has something to do with viewbobbing. When it's off, the bug doesn't occur.

**Comment by RottenAppleSalt** [comment]
just noticed this too. view bobbing off also makes them appear as normal for me.

**Comment by Qendolin** [comment]
Should be fixed: https://modrinth.com/mod/better-clouds/version/1.7.0+1.21-b

**Comment by Qendolin** [comment]
Please comment if this issue still occurs
