### ISSUE TITLE
Clouds turn black after some time | 1.20.1

### ISSUE THREAD

**Issue by JakeCarneAsada** [Qendolin/better-clouds#101]
## Describe the bug
> A clear and concise description of what the bug is
After about 5 minutes of playing the game, the clouds turn black & white.

## To Reproduce
> Steps to reproduce the behavior

1. Play the game
2. Fly around
3. Clouds instantly switch to a black & white color
...

### Expected behavior
> A clear and concise description of what you expected to happen.
Clouds remain white

### Screenshots
> If applicable, add screenshots to help explain your problem.
![image](https://github.com/Qendolin/better-clouds/assets/126632348/66d1d807-847f-4668-99d5-32dc2b62abcf)

### System Environment
- GPU: RTX 3070
- Mod Version: 1.0
- OS: Windows 11

*Optional*
- Shader:  Miniature
- Other Mods: Distant Horizons, Embeddium

### Additional context
> Add any other context about the problem here.

It should be noted that it happens weather clouds are on fast or fancy.

**Comment by Qendolin** [comment]
I can't reproduce this issue

**Comment by Qendolin** [comment]
Without any more details I can't attempt to fix this issue. Can you upload the game log after the issue occurs and maybe try using sodium instead?

**Comment by Qendolin** [comment]
Closing due to no response
