### ISSUE TITLE
mod causes stray stretched out polygons in the sky in negative z direction

### ISSUE THREAD

**Issue by CollinTheNewmaker** [Qendolin/better-clouds#103]
no shaders, no resource packs, fabric 1.20.6 ; mod version is 1.6.0-beta

**Comment by Qendolin** [comment]
I can't reproduce this issue

**Comment by Qendolin** [comment]
Can you send your game log and a screenshot of the F3 menu?

**Comment by Qendolin** [comment]
Closing due to no response
