### ISSUE TITLE
[BUG REPORT] 6/2/2024 : Flickering whilst Moving 1.20.6

### ISSUE THREAD

**Issue by makumaku1974** [Qendolin/better-clouds#106]
Im not using any shader and it is flickering whilst moving everywhere. I tested it with shaders and without. Still has the same issue.

**Comment by makumaku1974** [comment]
It is somehow fine on Water Block but I think you need to fix it with the Air Block.

**Comment by Qendolin** [comment]
Should be fixed: https://modrinth.com/mod/better-clouds/version/1.7.0+1.21-b

**Comment by Qendolin** [comment]
Please comment if this issue still occurs

**Comment by makumaku1974** [comment]
This is already fixed.
