### ISSUE TITLE
Incompatibility with Distant Horizons

### ISSUE THREAD

**Issue by unweeked** [Qendolin/better-clouds#107]
The Clouds from the mod render over the LOD-Chunks from Distant Horizons (using the latest version from their Discord) even when they're behind the LODs.
Using Better Clouds 1.0 and Distant Horizons 2.0.4-a-dev

**Comment by Finsider** [comment]
a temporary fix that I could find is to disable, and then enable DH rendering in DH' mod config, this works for me atleast
Better Clouds 1.4.9 - 1.20.2
Distant Horizon 2.1.0-a - 1.20.2

![2024-06-10_13 58 58](https://github.com/Qendolin/better-clouds/assets/91471471/d90731ef-3a80-4d11-b760-4fedb184b22d)
![2024-06-10_13 59 01](https://github.com/Qendolin/better-clouds/assets/91471471/e5001935-2337-4242-995f-307f408b3f07)
![2024-06-10_13 59 03](https://github.com/Qendolin/better-clouds/assets/91471471/06331f81-cafa-40d9-a1df-4c401159a21a)

**Comment by Qendolin** [comment]
Should be fixed: https://modrinth.com/mod/better-clouds/version/1.7.0+1.21-b

**Comment by Qendolin** [comment]
Please comment if this issue still occurs
