### ISSUE TITLE
Clouds Flicker When Walking with Nvidium

### ISSUE THREAD

**Issue by PhoebeJones** [Qendolin/better-clouds#108]
Hi!

I love your Better Clouds mod and recently tested the 1.20.6 version with a pack of client mods. It seems the clouds flicker, though, with Nvidium also installed. It is only when walking normally. Crouching, running, sprint-running, flying, and creative flight all are normal. 

I suspect it's Nvidium because they no longer flicker when it is disabled.

I've included snippets of the mod list and fabric loader.

![Screenshot 2024-06-05 125538](https://github.com/Qendolin/better-clouds/assets/55931760/85d708e5-1eae-4710-8660-36f7f8b1838d)
![Screenshot 2024-06-05 130107](https://github.com/Qendolin/better-clouds/assets/55931760/8bc84632-c283-4fa4-92d5-cad2d25364f9)

**Comment by REMDRIFT** [comment]
I am also experiencing this issue. It can be reproduced by enabling Nvidium and "View Bobbing".

**Comment by Qendolin** [comment]
Should be fixed: https://modrinth.com/mod/better-clouds/version/1.7.0+1.21-b

**Comment by Qendolin** [comment]
Tracking in #97
