### ISSUE TITLE
1.19 support

### ISSUE THREAD

**Issue by OsoaGH** [Qendolin/better-clouds#11]

**Comment by Qendolin** [comment]
I'm working on it. I want to switch to a proper config library like OwO or YACL.

**Comment by Qendolin** [comment]
I'm still working on it 😃, but there are still some issues and I'm using new (to me) rendering techniques.  
![image](https://user-images.githubusercontent.com/32160662/210248427-2fd497be-9754-415b-babc-f1ee822a250f.png)

My first attempt tried to sort the clouds for rendering but there is no way to make it fast enough, so now I'm trying order Independent transparency. Seems promising so far!

Once I got it looking how I want it I will begin migrating the config and I think I will (hopefully) be done before 1.20 releases.

**Comment by Secret-chest** [comment]
Any updates?

**Comment by Qendolin** [comment]
I'm very sorry for the delay. I have tackled some performance issues which requires rewriting a lot of the rendering. I am aiming for a <1 mspf target (on my GTX 1650) which I achieved but getting it to look nice is taking longer than expected. I'm on the edge of my graphics coding skills. However I still have my target set for a Minecraft 1.20 release

**Comment by Secret-chest** [comment]
Thank you. No pressure.

**Comment by Adamsapplespie** [comment]
Any updates? Was really excited to have found such a mod! :P

**Comment by Secret-chest** [comment]
@Qendolin please bring this best cloud mod to 1.19!

**Comment by Qendolin** [comment]
Thank you all very much for the interest in this update, I was quite busy and then forgot about it. I've now reached a point where I am happy with the updated looks but there is one possibly big task still ahead of me. 
I need to migrate to a new config system since my own slapped together config is causing too many problems. After that I should be ready to relase a beta version as I expect many bugs.

**Comment by Secret-chest** [comment]
1.20 is coming in a few weeks FYI.

**Comment by Qendolin** [comment]
https://modrinth.com/mod/better-clouds/version/1.1.0+1-19-4-B
Please test it out and see if you can find any bugs or other issues. I'ld especially appreciate feedback regarding the new settings menu and the translation strings.

**Comment by Pomi108** [comment]
Tried this mod out but can't get it to work? I'm using the required versions for all the dependencies but all I'm seeing are the vanilla clouds for some reason

**Comment by Qendolin** [comment]
MacOS is very likely the problem since Apple does not want to support OpenGL anymore but 4.1 is available on *some* devices which I *might* be able to support. You can open a separate issue if you want.

**Comment by Qendolin** [comment]
This is probably the last beta before the stable 1.19.4 release, just in time for 1.20
https://modrinth.com/mod/better-clouds/version/1.1.3+1.19.4-B

**Comment by Qendolin** [comment]
Done!!
https://modrinth.com/mod/better-clouds/version/1.2.0+1.19.4-R
