### ISSUE TITLE
Mod droped my FPS in half, and won't go back to normal.

### ISSUE THREAD

**Issue by CrisA-Works** [Qendolin/better-clouds#111]
## Description
> I have to heavily optimize my game to get a somewhat consistent 60 FPS. Since I installed the mod my FPS dropped to around 30, and it's been like that since then, even after removing the mod. Both with shaders enabled and disabled.

### System Environment
- GPU: AMD Radeon Vega 8 Graphics
- Mod Version: 1.5.8
- OS: Windows 10

*Optional:*
- Shader Pack: Miniature Shader 2.12
- Other Mods: They are a lot. They are all for Fabric 1.20.4 or were able to launch in that version.

Advanced Ui Scale 1.3.0
Ambient Sounds 5.3.9
Appleskin 2.5.1 *(MC 1.20.3)*
Bad Optimizations 2.1.1
Better F3 9.0.2
Better Third Person 1.9.0
Bookshelf 23.0.8
c2me 0.2.0 + alpha.11.67
Camera Overhaul 1.4.0
Cloth Config 13.0.121
Connected doors 1.2
Creative Core 2.11.26
Cristelib 1.2.4
Cull Leaves 3.3.0
Debugify 1.1
Dragonkind Evolved 1.3
Drip Sounds 1.19.4
Dungeons and Taverns 3.1.1
Dynamic FPS 3.4.3
Eating Animation 1.9.61
Enchantment Descriptions 20.0.4
Enhanced Block Entities 0.10
Entity Model Features 2.0.2
Entity Texture Features 6.0.1
Exordium 1.2.1
Fabric API 0.97.1
Fabric Language Kotlin 1.10.20
Ferrite Core 6.0.3
First Person 2.4.3
Immediatly Fast 1.2.18
Immersive Thunder 1.2.2
Indium 1.0.31
Iris 1.7.0
Ksyxis 1.3.2
Legacies Music 1.3.1
Lithium 0.12.1
Memory Leak Fix 0.24.0
Mouse Tweaks 2.26
mouse Wheelie 1.13.3
Noisium 2.0.3
No Telemetry 1.8.0
Not Enough Animations 1.7.3
Particle Core 0.1.2
Player Animation Lib 1.0.2
Precese Footsteps 1.9.4
Serious Player Animations 1.1.1
Sodium 0.5.8
Towns and Taverns 1.12.1.1
Tooltip Fix 1.1.1
Voice Chat 2.5.15
Xaeros World Map 1.38.8
Yet Another Config Lib 3.5.0
Yungs Api 4.4.3
Yungs Better Desert Temples 3.4.4
Yungs Better Strongholds 4.4.3

### Game Log / Crash Report
> [Unstable- Without Better Clouds Mod.log](https://github.com/user-attachments/files/15949055/Unstable-.Without.Better.Clouds.Mod.log)
[Unstable- With Better Clouds Mod.log](https://github.com/user-attachments/files/15949056/Unstable-.With.Better.Clouds.Mod.log)

**Comment by Qendolin** [comment]
If your games performance is bad after you have removed the mod then there must be another cause. BetterClouds doesn't cause any permanent changes to the game or your system that would make it possible to affect your game's performance after the mod is removed.

**Comment by CrisA-Works** [comment]
Well, time to reinstall MC then

Ugh....
