### ISSUE TITLE
BSL shader w. Curved world and Better Clouds does not play well together

### ISSUE THREAD

**Issue by Digital-Beast** [Qendolin/better-clouds#113]
## Describe the bug
MC Version 1.20.6
When using the BSL_v8.2.09p2 shader, and setting the 'World Curvature' setting to true, and in this case Size to 4096, the better clouds render only in the height between Y:176 and Y:222. Outside this height they are not visible regardless of setting in the mod, game and shader. 

## To Reproduce
> Steps to reproduce the behavior

1. Install Fabric API, Modmenu, Sodium, Sodium Extra, Indium, Iris & YetAnotherConfigLib-3.5.0+1.20.6-fabric
2. Install Better Clouds (better-clouds-1.6.0-beta+1.20.6.rev.28b0731)
3. Install BSL shader (BSL_v8.2.09p2 shader)
4: Navigate to BSL Shader settings -> Extra -> Enable curvature -> Set Size to 4096. 
5: Fly around to discover
(6:) Tested that no other mods have any influence on this

### Expected behavior
> A clear and concise description of what you expected to happen:
To be fair i expected the clouds to render as normal, (But maybe in a flay layer, however a curved layer would be suitable in my case) 

### Screenshots
> If applicable, add screenshots to help explain your problem.
Omitted as its just pictures with and without the better clouds rendered, in different heights, when curvature is on, and clouds rendered perfectly when curvature is off.

### System Environment
- GPU: MSI GTX 1660 Super
- Mod Version: 1.6.0-beta+1.20.6.rev.28b0731
- OS: Win10 Home, (22H2)

*Optional*
- Shader: (BSL_v8.2.09p2 shader)

- Other Mods: 
Extensive list of mods, to maybe enhance the game a little
[1.20.5-1.20.6]-preventer-1.1.0.jar
advancementinfo-1.20.4-fabric0.91.2-1.4.jar
AdvancementPlaques-1.20.6-fabric-1.6.2.jar
AmbientSounds_FABRIC_v6.0.1_mc1.20.6.jar
appleskin-fabric-mc1.20.5-3.0.2.jar
architectury-12.1.3-fabric.jar
ash_api-fabric-20.6.1-beta.jar
autokey-1.1.2+1.20.6.jar
badpackets-fabric-0.7.3.jar
balm-fabric-1.20.6-10.3.2.jar
betterbiomereblend-1.4.2.jar
better-clouds-1.6.0-beta+1.20.6.rev.28b0731.jar
BetterF1-1.0-1.20.6.jar
BetterF3-10.0.2-Fabric-1.20.6.jar
betterstats-3.11.1+fabric-1.20.6.jar
biomemoss-1.1.0.jar
blockmeter-1.13.1-1.20.6.jar
bobby-5.2.0+mc1.20.6.jar
c2me-fabric-mc1.20.6-0.2.0+alpha.11.96.jar
calcmod-1.3.2-beta+fabric.1.20.6.jar
capes-1.5.4+1.20.5-fabric.jar
Chat On Lost Focus-1.2.5.jar
chat_heads-0.12.3-fabric-1.20.6.jar
ChatNotify-Fabric-1.20.6-1.3.1.jar
chatpatches-206.6.5.jar
chattools-1.20.6-v2.2.0.jar
clean_tooltips-1.0-fabric-1.20.6.jar
clienttweaks-fabric-1.20.6-14.0.1.jar
close-btn-1.0.jar
cloth-config-14.0.126-fabric.jar
colorfulsubtitles-1.5.0.jar
continuity-3.0.0-beta.5+1.20.5.jar
craftingtweaks-fabric-1.20.6-21.0.1.jar
CreativeCore_FABRIC_v2.11.33_mc1.20.6.jar
CustomLevelColour-1.0.0+1.20.5.jar
CustomWindowTitle-Fabric-1.20+v1.2.0.jar
damagenumbers-1.3.0-fabric.jar
DarkTitleBar-1.2.jar
Debugify-1.20.6+1.0.jar
DetailArmorBar-2.6.3+1.20.6-fabric.jar
discerning-furnace-1.0.15+MC1.19-1.20.6.jar
DoAFlip-fabric-1.20.6-3.0.0.jar
drippyloadingscreen_fabric_3.0.4_MC_1.20.6.jar
DripSounds-1.19.4-0.3.2.jar
dynamiccrosshair-7.8.1+1.20.6-fabric.jar
dynamic-fps-3.4.3+minecraft-1.20.5-fabric.jar
eating-animation-1.20.6+1.9.7.jar
EffectTimerPlus-Fabric-1.20.5-1.1.2.jar
elytra_physics-fabric-2.0.jar
emissive-plugin-1.20.6-2.0.4-fabric.jar
emoji-type-2.2.4+1.20.6-fabric.jar
enhancedblockentities-0.10.1+1.20.6.jar
entity_model_features_fabric_1.20.5-2.0.2.jar
entity_texture_features_fabric_1.20.6-6.1.1.jar
entityculling-fabric-1.6.6-mc1.20.6.jar
expcounter-1.20.6-0-fabric.jar
explosive-enhancement-1.2.2-1.20.x.jar
ExtremeSoundMuffler-3.45.1-fabric-1.20.6.jar
fabric-api-0.100.0+1.20.6.jar
fabric-language-kotlin-1.10.20+kotlin.1.9.24.jar
fabricskyboxes-0.7.4+mc1.20.5.jar
fancymenu_fabric_3.2.3_MC_1.20.6.jar
fasterrandom-4.1.0.jar
Female-Gender-Mod-fabric-3.2.1+1.20.6.jar
ferritecore-6.1.1-fabric.jar
fluidvoidfading-1.1.5.jar
ForgeConfigAPIPort-v20.6.1-1.20.6-Fabric.jar
frank-1.0.0+1.20.2.jar
FuelInfo-2.1+1.20.6.jar
Gamma-Utils-1.8.20-mc1.20.5.jar
give-me-a-new-splash-text-1.1.0.jar
glowing-torchflower-mc1.20.6-1.0.0.jar
heywiki-fabric-1.5.1+1.20.6.jar
Highlighter-1.20.6-fabric-1.1.10.jar
IAS-Fabric-1.20.6-9.0.0-beta.5.jar
Iceberg-1.20.6-fabric-1.1.24.jar
ImmediatelyFast-Fabric-1.2.18+1.20.6.jar
immersive-winds-0.6.jar
indium-1.0.32+mc1.20.1.jar
iris-1.7.1+mc1.20.6.jar
journeymap-1.20.6-5.9.35-fabric.jar
keybind_fix-1.0.0.jar
konkrete_fabric_1.9.4_MC_1.20.5.jar
krypton-0.2.7.jar
LegendaryTooltips-1.20.6-fabric-1.4.6.jar
lighty-fabric-3.0.0-beta.3+1.20.6.jar
lithium-fabric-mc1.20.6-0.12.3.jar
maptooltip-fabric-1.20.5-3.1.0.jar
melody_fabric_1.0.6_MC_1.20.5.jar
memoryleakfix-fabric-1.17+-1.1.5.jar
MineMath-1.0.1-1.20.6.jar
modernfix-fabric-5.17.3+mc1.20.6.jar
modmenu-10.0.0-beta.1.jar
moreculling-1.20.5-0.25.0.jar
moremcmeta-1.20.6-4.4.7-fabric.jar
MouseTweaks-fabric-mc1.20.6-2.26.jar
music_control-1.8.1+1.20.6.jar
NoChatReports-FABRIC-1.20.6-v2.7.0.jar
no-feeding-baby-1.2.0.jar
notenoughcrashes-4.4.7+1.20.6-fabric.jar
Notes-1.20.6-2.1.0-fabric.jar
ObsidianUI-fabric-0.2.5+mc1.20.6.jar
oldmclogo-1.1.3.jar
owo-lib-0.12.9+1.20.5.jar
particle-moths-1.3.0+1.20.4.jar
particular-1.0.2+1.20.6.jar
physics-mod-3.0.14-mc-1.20.6-fabric.jar
Prism-1.20.5-fabric-1.0.7.jar
raised-fabric-24w10a-3.1.3.jar
reacharound+1.20.5-1.2.0.jar
real-arrow-tip-0.1.0+mc1.20.5.jar
reeses_sodium_options-1.7.2+mc1.20.5-build.103.jar
Resourcify (1.20.5-1.20.6-fabric)-1.4.0.jar
RyoamicLights-fabric-0.2.6+mc1.20.6.jar
shuffle-fabric-20.6.0.jar
shulkerboxtooltip-fabric-4.1.0-alpha.4+1.20.6.jar
shutupdeadentities-mc1.20.5+1.1.jar
skinlayers3d-fabric-1.6.6-mc1.20.6.jar
slotted-armor-hud-1.2.1.jar
SmoothScrollingRefurbished+1.20.6-1.1.3.jar
smoothskies-1.1.0.jar
sodium-extra-0.5.6+mc1.20.6.jar
sodium-fabric-0.5.9+mc1.20.6.jar
sodium-shadowy-path-blocks-3.3.0.jar
sound-physics-remastered-fabric-1.20.6-1.4.2.jar
stendhal-1.4.1-1.20.6.jar
tcdcommons-3.11+fabric-1.20.6.jar
threadtweak-fabric-1.20.6-0.1.3.jar
tia-1.20-1.1-fabric.jar
timm-1.0.3 for 1.20.5+1.20.6.jar
toomanybinds-0.3.4+1.20.2.jar
ViaFabricPlus-3.3.1.jar
vistas-2.6.1.jar
visuality-0.7.4+1.20.5.jar
water_vision-1.1.0+1.20.6.jar
waveycapes-fabric-1.4.7-mc1.20.6.jar
world_preview-fabric-1.20.6-1.2.2.jar
wthit-fabric-11.3.1.jar
xplus-autofish-1.1.0-fabric-1.20.5.jar
YetAnotherConfigLib-3.5.0+1.20.6-fabric.jar
Zoomify-2.13.5+1.20.6.jar
better-mipmaps-0.2-1.20.6.jar.zip

### Additional context
> Add any other context about the problem here.
A lot of different texture packs are used as well, but in my testing they had no influence, but let me know if you need them

Edit: Clarification & Added forgotten info

**Comment by Qendolin** [comment]
I haven't checked this out, but it might be fixed in the newest release. If not, it's quite likely that there is nothing I can do about it.

**Comment by Qendolin** [comment]
I can implement a partial workaround. Clouds would render like normal (so without curvature) and performance would be slightly worse.
![image](https://github.com/Qendolin/better-clouds/assets/32160662/0544c6b8-b2fe-43ed-930f-300a60ade58b)

**Comment by Digital-Beast** [comment]
Hey Qendolin, this is perfect for my case! 

Thank you so much!

**Comment by Qendolin** [comment]
Perfect, it's gonna be in the next release. In the settings under "Performance" there will be a new option called "Frustum Culling", you will want to turn that off. Again sorry that it's not possible to support it properly, but that would require shaderpack-specific code which simply requires too much maintenance.

**Comment by Qendolin** [comment]
![image](https://github.com/Qendolin/better-clouds/assets/32160662/9af83db1-aa2d-4d40-82cd-78a6b9cf963b)
I just had a look at the BSL code for world curvature, and it's actually trivially easy to implement. I think I might add it just for the fun of it

**Comment by Qendolin** [comment]
Published https://modrinth.com/mod/better-clouds/version/1.7.1+1.21-r

**Comment by Qendolin** [comment]
https://modrinth.com/mod/better-clouds/version/1.6.2+1.20.6-r

**Comment by Qendolin** [comment]
In the next version frustum culling will be disabled automatically when a shader pack requires it.
