### ISSUE TITLE
request: clouds get darker when Wither appears

### ISSUE THREAD

**Issue by peow** [Qendolin/better-clouds#114]
* When the Wither appears in Minecraft Vanilla, the edge of the sky becomes darker, and the clouds in the corner also darken, giving an immersive feel.

https://github.com/Qendolin/better-clouds/assets/105888751/b2c6afa8-cc51-4b04-928d-0d79554680f5

* for some reason, when Sodium is present, when the Wither is summoned all the clouds darken, and this increases the immersion even more, giving a sense of danger to the battle

https://github.com/Qendolin/better-clouds/assets/105888751/c9b49ac1-cc97-4daa-9920-645477f73237

* but with the Better Clouds mod, no clouds darken when the Wither appears, so if you summon him during the day, the sky stay extremely bright during the battle, taking away from the immersion

https://github.com/Qendolin/better-clouds/assets/105888751/031d81d4-3daa-42fe-9793-c6de6b4650ca

if the clouds darkened it would be extremely epic

![huge_2024-06-26_19 39 29](https://github.com/Qendolin/better-clouds/assets/105888751/9c5f6a34-5cd8-4a24-80b6-8f956a9566c7)

**Comment by Qendolin** [comment]
Ok will be in the next release, but the effect will not be so strong. I've decided to take into account multiple color sources. The sky color, the fog color and the clouds color. I also quickly look at sodium's code and did not see any reason for why the clouds would get darker, so I'm not even sure if that's a feature or a bug with sodium.

**Comment by Qendolin** [comment]
Added in https://modrinth.com/mod/better-clouds/version/1.7.0+1.21-b

**Comment by Qendolin** [comment]
https://modrinth.com/mod/better-clouds/version/1.3.18+1.20.1-R
