### ISSUE TITLE
Better Clouds are not visible on fabulous graphics - 1.21

### ISSUE THREAD

**Issue by ErakAcheron** [Qendolin/better-clouds#117]
## Issue:
Clouds do not render on the fabulous graphics setting. 

## To Reproduce
Enable fabulous graphics on Minecraft 1.21 with the modrinth 1.21 beta of Better Clouds.

### Expected behavior
Better Clouds would render as normal.

### Screenshots
![image](https://github.com/Qendolin/better-clouds/assets/116046390/92402bf2-a113-4225-8f4e-20dc2cac9dff)
![image](https://github.com/Qendolin/better-clouds/assets/116046390/da5f96e7-3acb-47b7-9757-1d487a620350)

### System Environment
- GPU: 
![image](https://github.com/Qendolin/better-clouds/assets/116046390/5e77b1b9-001f-42b5-8b11-abccbdd8c107)
- Mod Version: Beta 1.7.0 for Minecraft 1.21
- OS: Windows 10

## Other Mods: 
Sodium (+sodium extra, +sodium options), Iris, Bobby, Lithium, Indium, Simple Fog Control, Entity Culling and Immediately Fast should be all the major performance / rendering mods I was running. 

While I'm here, thank you very much for the 1.21 port!

**Comment by ErakAcheron** [comment]
![2024-06-28_22 24 04](https://github.com/Qendolin/better-clouds/assets/116046390/7edbda7c-0a3b-4d62-8e91-6448a803b24e)
![2024-06-28_22 24 10](https://github.com/Qendolin/better-clouds/assets/116046390/94319d4c-01aa-44ef-b7ef-6cfc1e433c9f)

Retested with only require mods just to ensure it wasn't some other mod messing with rendering, the issue persists unfortunately.

**Comment by Qendolin** [comment]
I guess for now you can just play on fancy graphics, other than worse performance Fabulous graphics doesn't even do much

**Comment by ErakAcheron** [comment]
I mean yeah, this isn't a massive bug by any means (especially since anyone with shaders is stuck on fancy anyways), but I figured it was better to report it than not.

**Comment by Qendolin** [comment]
Should be fixed https://modrinth.com/mod/better-clouds/version/1.7.1+1.21-r

**Comment by ErakAcheron** [comment]
Just downloaded the latest version and the fix works for me, thank you!
