### ISSUE TITLE
Iris together with Distant Horizons cause rendering issue

### ISSUE THREAD

**Issue by Konijnebeer** [Qendolin/better-clouds#118]
## Describe the bug
> A clear and concise description of what the bug is
The Mod seems to stop rendering clouds beyond a certain point when having ComplementaryReimagined_r5.2.1 turned on using Sodium and Iris and distanr horizons

## To Reproduce
> Steps to reproduce the behavior

1. Make sure DH is on
2. Turn shaders on
3. See that part of the clouds stop rendering (the area moves around with you)

### Expected behavior
Clouds keep rendering where they should and not cut off

### Screenshots
> If applicable, add screenshots to help explain your problem.
![image](https://github.com/Qendolin/better-clouds/assets/98305413/c88aac6d-4863-46cf-99d7-9979ba2958dd)

### System Environment
- GPU: NVIDIA RTX 3060 laptop
- Mod Version: better-clouds-1.7.0-beta+1.21.rev.5c74a25
- OS: Windows 11

*Optional*
- Shader: ComplementaryReimagined_r5.2.1
- Other Mods:    [✔] better-clouds-1.7.0-beta+1.21.rev.5c74a25
  [✔] bobby-5.2.2+mc1.21
  [✔] cloth-config-15.0.127-fabric
  [✔] DistantHorizons-2.1.2-a-1.21-neo-fabric
  [✔] fabric-api-0.100.4+1.21
  [✔] indium-1.0.33+mc1.21
  [✔] iris-1.7.1+mc1.21
  [✔] lithium-fabric-mc1.21-0.12.7
  [✔] modmenu-11.0.1
  [✔] placeholder-api-2.4.0+1.21
  [✔] sodium-fabric-0.5.9+mc1.21
  [✔] YetAnotherConfigLib-3.5.0+1.21-fabric

### Additional context
> Add any other context about the problem here.

**Comment by Qendolin** [comment]
I have confirmed this issue. Weird that it didn't happen during my testing.

**Comment by Qendolin** [comment]
Ok so this will likely still be an issue until the next DH or Iris release. I can't really fix this. If it takes too long I'll probably add a workaround.

**Comment by Konijnebeer** [comment]
Oke sounds good, Ty for looking into it!

**Comment by Qendolin** [comment]
Progress has been made, the DH Dev has made a fix but I can't test it out until iris has also updated.

**Comment by Qendolin** [comment]
Okay I've found a fix, new release coming soon probably

**Comment by Qendolin** [comment]
Should be fixed https://modrinth.com/mod/better-clouds/version/1.7.1+1.21-r
