### ISSUE TITLE
Game crash when trying to disable "Better Clouds"

### ISSUE THREAD

**Issue by Nilsson321** [Qendolin/better-clouds#122]
## Description
The game crash when i try to disable the option "Better Clouds".

### Game Log / Crash Report
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2024-07-03 21:29:22
Description: Unexpected error

java.lang.IllegalStateException: BufferBuilder was empty
	at net.minecraft.class_287.method_60800(class_287.java:69)
	at me.jellysquid.mods.sodium.client.render.immediate.CloudRenderer.render(CloudRenderer.java:100)
	at net.minecraft.class_761.method_3259(class_761.java:16180)
	at net.minecraft.class_761.method_22710(class_761.java:1260)
	at net.minecraft.class_757.method_3188(class_757.java:1087)
	at net.minecraft.class_757.method_3192(class_757.java:850)
	at net.minecraft.class_310.method_1523(class_310.java:1285)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_287.method_60800(class_287.java:69)
	at me.jellysquid.mods.sodium.client.render.immediate.CloudRenderer.render(CloudRenderer.java:100)
	at net.minecraft.class_761.method_3259(class_761.java:16180)
	at net.minecraft.class_761.method_22710(class_761.java:1260)
	at net.minecraft.class_757.method_3188(class_757.java:1087)

-- Uptime --
Details:
	JVM uptime: 6679.405s
	Wall uptime: 6663.812s
	High-res time: 6659.228s
	Client ticks: 132722 ticks / 6636.100s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2501)
	at net.minecraft.class_310.method_54580(class_310.java:949)
	at net.minecraft.class_310.method_1514(class_310.java:905)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 6 total; [class_746['Nilsson321'/125828, l='ClientLevel', x=453.44, y=55.00, z=-418.39], class_745['RustyFork21'/123750, l='ClientLevel', x=450.00, y=55.00, z=-409.32], class_745['Welcyx'/48742, l='ClientLevel', x=452.50, y=56.00, z=-402.50], class_745['SebaLaw17'/127416, l='ClientLevel', x=454.50, y=56.00, z=-401.50], class_745['123MadMax'/96578, l='ClientLevel', x=487.64, y=57.97, z=-420.80], class_745['Gjmc00_Dughmosh'/127714, l='ClientLevel', x=452.50, y=56.00, z=-398.50]]
	Chunk stats: 4096, 809 F: 116 L: 0 U: 373 C: 0
	Level dimension: minecraft:overworld
	Level spawn location: World: (449,56,-404), Section: (at 1,8,12 in 28,3,-26; chunk contains blocks 448,-64,-416 to 463,319,-401), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 2245872 game time, 52000 day time
	Server brand: BungeeCraft (8fcc17a)
	Server type: Non-integrated multiplayer server
	Tracked entity count: 344

-- Last reload --
Details:
	Reload number: 2
	Reload reason: manual
	Finished: Yes
	Packs: vanilla, fabric, ambientsounds, betterclouds, bobby, com_viaversion_viabackwards-common, com_viaversion_viaversion-common, continuity, cool_elytra, creativecore, entity_model_features, entity_texture_features, entityculling, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fabricskyboxes, forcecloseworldloadingscreen, freelook, healthindicators, higher-chat, immediatelyfast, indium, iris, itemscroller, litematica, lithium, malilib, midnightlib, minihud, modmenu, morechathistory, net_raphimc_viaaprilfools, net_raphimc_viabedrock, net_raphimc_vialegacy, org_apache_commons_commons-math3, removewardeneffect, simple-armor-hud, skyblocker, sodium, sound_physics_remastered, syncmatica, tooltipscroll, tweakeroo, viafabricplus, xaerominimap, yet_another_config_lib_v3, continuity:default, continuity:glass_pane_culling_fix, file/FreshAnimations_v1.9.1, file/Colorful_Textures_1.19.2, file/VanillaTweaks_r539778_MC1.21.x, file/Nebulous Skys 1.0, server/00000000/c45fe627-5aee-3015-a209-65017879de96

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 301358200 bytes (287 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600 6-Core Processor              
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1650 SUPER
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 4096.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 31.0.15.3770
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Virtual memory max (MiB): 22390.63
	Virtual memory used (MiB): 17091.07
	Swap memory total (MiB): 14336.00
	Swap memory used (MiB): 1338.68
	Space in storage for jna.tmpdir (MiB): available: 46323.21, total: 242921.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 46323.21, total: 242921.00
	Space in storage for io.netty.native.workdir (MiB): available: 46323.21, total: 242921.00
	Space in storage for java.io.tmpdir (MiB): available: 46323.21, total: 242921.00
	Space in storage for workdir (MiB): available: 46323.21, total: 242921.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		ambientsounds: AmbientSounds 6.0.2
		betterclouds: Better Clouds 1.7.0-beta+1.21.rev.5c74a25
		bobby: Bobby 5.2.2+mc1.21
			com_typesafe_config: config 1.4.2
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.27+6a6dfa1990
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		continuity: Continuity 3.0.0-beta.5+1.21
		cool_elytra: Cool Elytra 1.5.1
			midnightlib: MidnightLib 1.5.7
		creativecore: CreativeCore 2.11.34
			net_neoforged_bus: bus 7.2.0
		entity_model_features: Entity Model Features 2.1
		entity_texture_features: Entity Texture Features 6.1.2
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling 1.6.6
		fabric-api: Fabric API 0.100.3+1.21
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.67+b5597344d1
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.28+6fc22b99d1
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a7d1
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8cd1
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a7d1
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8cd1
			fabric-command-api-v1: Fabric Command API (v1) 1.2.48+f71b366fd1
			fabric-commands-v0: Fabric Commands (v0) 0.2.65+df3654b3d1
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.13+b5597344d1
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.14+7f945d5bd1
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.3.1+8a3b5617d1
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a7d1
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.23+6a6dfa19d1
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.8+16c4ae25d1
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b99d1
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b99d1
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.10+e633f883d1
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.52+6573ed8cd1
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc921d1
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.1+cb5ced13d1
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a7d1
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b3d1
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.11+8f3583aed1
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.10+6573ed8cd1
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8cd1
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6bd1
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.0+ab7edbacd1
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.1.11+d1321076d1
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8cd1
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.9+6573ed8cd1
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.0.22+ab7edbacd1
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.16+fe474d6bd1
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.6.4+48fb1586d1
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.66+df3654b3d1
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2ed1
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b5597344d1
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.69+df3654b3d1
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.3+d1321076d1
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.2.1+d153f344d1
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.1.4+cb5ced13d1
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b5597344d1
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.79+b5597344d1
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8cd1
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.14+b5597344d1
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.0.12+6573ed8cd1
		fabricloader: Fabric Loader 0.15.11
			mixinextras: MixinExtras 0.3.5
		fabricskyboxes: FabricSkyBoxes 0.7.4+mc1.21
		ferritecore: FerriteCore 7.0.0
		forcecloseworldloadingscreen: kennytv's epic force close loading screen mod for Fabric 2.2.2
		freelook: Freelook 1.2.2
		healthindicators: Health Indicators 3.3.0
		higher-chat: Higher Chat 1.5
		immediatelyfast: ImmediatelyFast 1.2.18+1.21
			net_lenni0451_reflect: Reflect 1.3.4
		indium: Indium 1.0.33+mc1.21
		iris: Iris 1.7.1+mc1.21
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		itemscroller: Item Scroller 0.23.999-sakura.2
		java: OpenJDK 64-Bit Server VM 21
		litematica: Litematica 0.18.999-sakura.11
		lithium: Lithium 0.12.7
		malilib: MaLiLib 0.19.999-sakura.4
		minecraft: Minecraft 1.21
		minihud: MiniHUD 0.31.999-sakura.3
		modmenu: Mod Menu 11.0.1
			placeholder-api: Placeholder API 2.4.0-pre.2+1.21
		morechathistory: More Chat History 1.3.1
		removewardeneffect: Remove Warden Darkness 0.0.2-1.20.6
		simple-armor-hud: Simple armor hud 1.21-1.4.5
		skyblocker: Skyblocker 1.21.0+1.21
			com_logisticscraft_occlusionculling: occlusionculling 0.0.8-SNAPSHOT
			meteordevelopment_discord-ipc: discord-ipc 1.1
			moe_nea_neurepoparser: neurepoparser 1.5.0
			org_apache_commons_commons-math3: commons-math3 3.6.1
			org_eclipse_jgit_org_eclipse_jgit: org.eclipse.jgit 6.9.0.202403050737-r
		sodium: Sodium 0.5.9+mc1.21
		sound_physics_remastered: Sound Physics Remastered 1.21-1.4.3
		syncmatica: Syncmatica 0.3.12-sakura.4
		tooltipscroll: Tooltip Scroll 1.3.0+1.21
		tweakeroo: Tweakeroo 0.20.999-sakura.8
		viafabricplus: ViaFabricPlus 3.4.1
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			com_vdurmont_semver4j: semver4j 3.1.0
			com_viaversion_viabackwards-common: viabackwards-common 5.0.1
			com_viaversion_viaversion-common: viaversion-common 5.0.1
			de_florianmichael_classic4j: Classic4J 2.0.2
			io_jsonwebtoken_jjwt-api: jjwt-api 0.12.3
			io_jsonwebtoken_jjwt-gson: jjwt-gson 0.12.3
			io_jsonwebtoken_jjwt-impl: jjwt-impl 0.12.3
			io_netty_netty-codec-http: netty-codec-http 4.1.111
			net_jodah_expiringmap: expiringmap 0.5.10
			net_lenni0451_commons_httpclient: httpclient 1.4.1
			net_lenni0451_mcping: MCPing 1.4.0
			net_lenni0451_mcstructs-bedrock_forms: forms 1.2.0
			net_lenni0451_mcstructs-bedrock_text: text 1.2.0
			net_raphimc_minecraftauth: MinecraftAuth 4.0.0
			net_raphimc_viaaprilfools: ViaAprilFools 3.0.0
			net_raphimc_viabedrock: ViaBedrock 0.0.9-SNAPSHOT
			net_raphimc_vialegacy: ViaLegacy 3.0.1
			net_raphimc_vialoader: ViaLoader 3.0.1
			org_cloudburstmc_netty_netty-transport-raknet: netty-transport-raknet 1.0.0.CR3-SNAPSHOT
			org_iq80_leveldb_leveldb: leveldb 0.12
			org_iq80_leveldb_leveldb-api: leveldb-api 0.12
			org_lz4_lz4-pure-java: lz4-pure-java 1.8.0
			org_yaml_snakeyaml: snakeyaml 2.2
		xaerominimap: Xaero's Minimap 24.2.1
		yet_another_config_lib_v3: YetAnotherConfigLib 3.5.0+1.21-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
	Loaded Shaderpack: (off)
	Launched Version: fabric-loader-0.15.11-1.21
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: NVIDIA GeForce GTX 1650 SUPER/PCIe/SSE2 GL version 3.2.0 NVIDIA 537.70, NVIDIA Corporation
	Window size: 1920x1080
	GFLW Platform: win32
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. <texture> is not a valid texture name.' x 2
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Render Distance: 46/46 chunks
	Resource Packs: vanilla, fabric, ambientsounds, betterclouds, bobby, com_viaversion_viabackwards-common, com_viaversion_viaversion-common, continuity, cool_elytra, creativecore, entity_model_features, entity_texture_features, entityculling, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fabricskyboxes, forcecloseworldloadingscreen, freelook, healthindicators, higher-chat, immediatelyfast, indium, iris, itemscroller, litematica, lithium, malilib, midnightlib, minihud, modmenu, morechathistory, net_raphimc_viaaprilfools, net_raphimc_viabedrock, net_raphimc_vialegacy, org_apache_commons_commons-math3, removewardeneffect, simple-armor-hud, skyblocker, sodium, sound_physics_remastered, syncmatica, tooltipscroll, tweakeroo (incompatible), viafabricplus, xaerominimap (incompatible), yet_another_config_lib_v3 (incompatible), continuity:default, continuity:glass_pane_culling_fix, file/FreshAnimations_v1.9.1, file/Colorful_Textures_1.19.2 (incompatible), file/VanillaTweaks_r539778_MC1.21.x, file/Nebulous Skys 1.0 (incompatible), server/00000000/c45fe627-5aee-3015-a209-65017879de96 (incompatible)
	Current Language: en_us
	Locale: sv_SE
	System encoding: Cp1252
	File encoding: UTF-8
	CPU: 12x AMD Ryzen 5 3600 6-Core Processor

**Comment by Qendolin** [comment]
I'm assuming you are talking about this setting?
![image](https://github.com/Qendolin/better-clouds/assets/32160662/cbab68ad-17db-40c1-a04a-2bd73236c17e)

**Comment by Nilsson321** [comment]
Yes

**Comment by Qendolin** [comment]
Does that happen consistently? I haven't been able to reproduce this issue.

**Comment by Nilsson321** [comment]
Only when i try doing this on a server / enable it and connect to a server

**Comment by Nilsson321** [comment]
I managed to fix the problem!

**Comment by Qendolin** [comment]
Can you please tell me how?

**Comment by Nilsson321** [comment]
Updated Sodium, Indium and Lithium
