### ISSUE TITLE
Compatibility issues with Sodium Extra 1.21

### ISSUE THREAD

**Issue by SadMilklad** [Qendolin/better-clouds#128]
The better clouds mod is not yet compatible with the Sodium Extra mod in 1.21 - particularly when rendering the clouds at different y-levels. Previous versions of Better Clouds have been compatible with Sodium Extra and this feature.

**Comment by Qendolin** [comment]
Thanks for reporting this issue, I'll look into it. Just note that you can adjust the cloud y level in BC's settings as well (I believe in the "generation" tab)

**Comment by Qendolin** [comment]
I don't like how GH automatically closes issues :(

**Comment by TOMahawkCatz** [comment]
adding to this thread, the sodium extra incompatibility staggers the better clouds upwards, so that when the cloud height is set to -64 in mod menu, the clouds actually appear at something like y=100 in game

**Comment by TomOnMars** [comment]
new account
I was lying - sodium extra isn't causing my height offset issue

**Comment by Qendolin** [comment]
I think I've fixed this bug, can't remember

**Comment by Ricarius** [comment]
Writing to say that I am experiencing the same issue currently. I found that the features added by Better Clouds are not rendering properly while Sodium Extra is enabled, as the rendering issue goes away once I disable Sodium Extra in my modpack. I am on 1.21.3 and using Better Clouds release version 1.8.2 alongside Sodium Extra release version 0.6.0.
