### ISSUE TITLE
"Wigglyness" Reduction config!

### ISSUE THREAD

**Issue by HyperDashPony** [Qendolin/better-clouds#129]
Hi! I love your mod, but something about how the cubes grow and shrink is just strange to me. I'm not sure if it's possible to add a config to this because of the way you're probably using noise to generate the clouds, but if there's a way for it to be done that would be absolutely amazing! Thank you for all your hard work!

**Comment by Qendolin** [comment]
I think the option you're looking for is called "Wind Effect" or something like that. Should be in the appearance section.

**Comment by HyperDashPony** [comment]
Thank you! Sorry!
