### ISSUE TITLE
All resource packs forcibly unloaded on startup [1.19.4]

### ISSUE THREAD

**Issue by PencilVoid** [Qendolin/better-clouds#13]
[Game log](https://mclo.gs/a7VP9Db)
Minecraft 1.19.4
Quilt Loader 0.18.10

**Comment by Qendolin** [comment]
Can you upload a screenshot of your F3 screen? I need to check your GPU and driver version

**Comment by Qendolin** [comment]
Can you check if the issue persists in the latest build: https://modrinth.com/mod/better-clouds/version/1.1.1+1-19-4-B

**Comment by PencilVoid** [comment]
The issue doesn't occur in the latest build. However, I noticed that while walking at night the light surrounding the moon moves moves about, causing it to not be aligned with the moon.

Here is my F3 screen just in case:
![2023-05-27_16 16 05](https://github.com/Qendolin/better-clouds/assets/83508866/e635f229-5c82-4f3c-a8e8-3863d3bce9ee)

**Comment by Qendolin** [comment]
Thanks, I'll close this issue now. Can you open a new issue regarding your other problem ("I noticed that while walking at night the light surrounding the moon moves moves about, causing it to not be aligned with the moon.") ?
