### ISSUE TITLE
Dotted / Noisy / Dithered clouds at far distances

### ISSUE THREAD

**Issue by ricardotimmr** [Qendolin/better-clouds#137]
## Describe the bug
> Clouds that are further away from the player seem to be generating with a kind of "dotty" pattern in them

## To Reproduce
> No steps needed. I just loaded into the world.

### Expected behavior
> The clouds that are further away should generate in the same clean texture pattern like those that are near the player

### Screenshots
> If applicable, add screenshots to help explain your problem.
![2024-08-19_13 18 34](https://github.com/user-attachments/assets/030a7589-f212-4bcf-a61d-082c9450ba3b)
![2024-08-19_13 18 36](https://github.com/user-attachments/assets/2a4c89b6-eb38-42a0-92ec-42a2c028d47b)
![2024-08-19_13 18 43](https://github.com/user-attachments/assets/833a57c9-aba1-48f9-a418-8ed91bbb6822)

### System Environment
- GPU: NVIDIA GeForce RTX 3060 TI
- Mod Version: 1.5.10
- OS: Windows 11

*Optional*
- Shader: No shader applied
- Other Mods: Adventure Redefined, AmbienSounds, Axiom, Blur, Bobby, EntityCulling, Essential, FerritCore, FogLooksGoodNow, FPS Reducer, Freecam, Indiu, Iris, Item Scroller, LayzDFU, Litematica, Lithium, Logical Zoom, MaLiLib, Mineblocks Repeated Utilities, MiniHUD, Mod Menu, Satin, Shulker Box Tooltip, Sodium, Tweakeroo, WorldEdit

### Additional context
> Add any other context about the problem here.

**Comment by Qendolin** [comment]
Thank you for the report, but this behaviour is intended. It's called dithering, and due to the way that I render the clouds, all of then must have the same opacity. So to fade them in and out I don't have a different option.
