### ISSUE TITLE
Sunrise/Sunset start and end time options are borked.

### ISSUE THREAD

**Issue by rabbit-time** [Qendolin/better-clouds#138]
## Describe the bug
The sunrise/sunset start and end time options cannot be changed in the config menu and do not change anything even if edited directly through the config file itself.

## To Reproduce
1. Load game
2. Try to change the aforementioned options
3. Try to change them in the config file
4. Test

### Expected behavior
The options were meant to work.

### System Environment
- GPU: AMD Radeon 7900 XTX
- Mod Version: 1.3.19+1.20.1
- OS: Windows 11

### Additional context
I have other mods enabled such as Time and Wind. Additionally, after editing the config file, I tried reloading the config using commands and by restarting the game to see if changes would take effect.

**Comment by Qendolin** [comment]
The config is working as intended, the sunset and sunrise times interpolate the day and night brightness. Since day and night brightness are by default 100% no effect is observed.
I'll improve it so that the coloring of the clouds is also affected.

**Comment by rabbit-time** [comment]
I did want to change those options since at some points during sunrise and sunset, the clouds have a very wrong color and look out of place.

Should have also mentioned I'm using Complimentary Reimagined shaders.

**Comment by Qendolin** [comment]
Should be better now
