### ISSUE TITLE
Modpack use permission 

### ISSUE THREAD

**Issue by GreatSaltyLake** [Qendolin/better-clouds#139]
Looking for permission to use in my pack that I am in the process of prepping for public availability on Modrinth. Please reach out with any questions or concerns regarding the pack. Some info is available on my Github page under "A Pleasant Day". Thanks!

**Comment by Qendolin** [comment]
You can, the terms are here: 
https://github.com/Qendolin/better-clouds/wiki/Mod-Integration#use-in-modpacks
