### ISSUE TITLE
Weird Sky Glitch/No Clouds

### ISSUE THREAD

**Issue by SmarterCob** [Qendolin/better-clouds#143]
## Describe the bug
> Whenever I join a world or a server, the sky around blocks and entities begin to act weird. These cubes form around the blocks/entities that kind of move around the border of the blocks/entities.

## To Reproduce
> Steps to reproduce the behavior

1. Load Minecraft
2. Join a world/server
3. Look up
...

### Expected behavior
> No weird sky glitches and some really nice clouds.

### Screenshots
> I recorded a video but it won't let me put it here because the file size is too big so I made a drive link to watch it.
[https://drive.google.com/file/d/17NrA2vKylYbOTAxzCuxbWRYxJ03mXs8y/view?usp=sharing](https://drive.google.com/file/d/17NrA2vKylYbOTAxzCuxbWRYxJ03mXs8y/view?usp=sharing)
However, if you don't trust the link or you don't want to watch the video, I have screenshots too, but I recommend watching the video as it's more noticeable there.
![Screenshot (5)](https://github.com/user-attachments/assets/269c6dba-d462-496d-a3eb-5e094c6a2228)
![Screenshot (6)](https://github.com/user-attachments/assets/e7a4afe3-cd68-47ea-b2f9-8aa0888ea17d)

### System Environment
- GPU: AMD Radeon Graphics
- Mod Version: 1.7.1 for 1.21
- OS: Windows 11

*Optional*
- Shader: 
- Other Mods: 
architectury-13.0.6-fabric.jar                                       
balm-fabric-1.21.1-21.0.18.jar                                       
better-clouds-1.7.1+1.21.jar                                         
betterstats-3.13.2+fabric-1.21.jar                                   
cloth-config-15.0.130-fabric.jar                                     
continuity-3.0.0-beta.5+1.21.jar                                     
devtools-1.0.0.jar                                                   
dynamic-fps-3.6.3+minecraft-1.21.0-fabric.jar                        
dynamiclights-v1.8.3-mc1.17x-1.21x-mod.jar                           
entityculling-fabric-1.7.0-mc1.21.jar                                
essential_1-3-4-1_fabric_1-21-1.jar                                  
fabric-api-0.102.0+1.21.jar                                          
fabric-language-kotlin-1.12.1+kotlin.2.0.20.jar                      
fallingleaves-1.16.2+1.21.jar                                        
ferritecore-7.0.0-fabric.jar                                         
flashback-0.3.0.jar                                                  
Highlighter-1.21-fabric-1.1.11.jar                                   
Iceberg-1.21-fabric-1.2.5.jar                                        
ImmediatelyFast-Fabric-1.2.21+1.21.1.jar                             
indium-1.0.35+mc1.21.jar                                             
inventoryessentials-fabric-1.21-21.0.2.jar                           
iris-fabric-1.8.0-beta.3+mc1.21.1.jar                                
litematica-fabric-1.21.1-0.19.50.jar                                 
litematica-printer-1.21-3.5.0-sakura.4.jar                           
lithium-fabric-mc1.21-0.13.0.jar                                     
malilib-fabric-1.21.1-0.21.0.jar                                     
modernfix-fabric-5.19.1+mc1.21.jar                                   
modmenu-11.0.2.jar                                                   
moreculling-1.21-0.27.1.jar                                          
placeholder-api-2.4.1+1.21.jar                                       
reeses-sodium-options-fabric-1.8.0-beta.2+mc1.21.1.jar               
shulkerboxtooltip-fabric-5.0.4+1.21.jar                              
sodium-extra-fabric-0.6.0-beta.1+mc1.21.1.jar                        
sodium-fabric-0.6.0-beta.1+mc1.21.jar                                
tcdcommons-3.12.3+fabric-1.21.jar                                    
voicechat-fabric-1.21.1-2.5.20.jar                                   
XaerosWorldMap_1.39.0_Fabric_1.21.jar                                
Xaeros_Minimap_24.3.0_Fabric_1.21.jar                                
YetAnotherConfigLib-3.5.0+1.21-fabric.jar

### Additional context
> I use Modrinth as a Minecraft launcher. I highly doubt this could be the issue but it might be helpful to know.

**Comment by Qendolin** [comment]
Can you attach a screenshot of your f3 menu? This is probably the same issue as #57

**Comment by SmarterCob** [comment]
Yeah of course
![2024-09-03_22 28 21](https://github.com/user-attachments/assets/0044a4aa-1761-44f9-b420-dc69006de1a0)

**Comment by SmarterCob** [comment]
It seems to be the same graphics driver and the same issue as #57. Sorry, I didn't notice. I read through it, does that mean there isn't a fix yet?

**Comment by Qendolin** [comment]
Yes, it seems to be an issue with AMD 3000 series integrated GPUs. Multiple attempts didn't fix the issue. I don't have an affected GPU so I can't do anything more. Sorry
