### ISSUE TITLE
Clouds not working normally when rain

### ISSUE THREAD

**Issue by An0therOne** [Qendolin/better-clouds#149]
## Describe the bug
> Clouds not working normally when raining

## To Reproduce
> Steps to reproduce the behavior

1. /Weather rain
2. Clouds not working
3. Move the player to be on water
4. Clouds now working, but only on water

### Expected behavior
> For the clouds to work normally whether on water or not

### Screenshots
> If applicable, add screenshots to help explain your problem.
![Screenshot_115](https://github.com/user-attachments/assets/9121b11d-6146-419e-b526-6686f1094ebc)
![Screenshot_114](https://github.com/user-attachments/assets/bad5b2b0-5f6e-450f-a93c-fb4f39cd137e)

### System Environment
- GPU: AMD Ryzen 3 3200G with Radeon Vega Graphics 3.60 GHz
- Mod Version: better-clouds-1.3.17+1.20.1
- OS: Windows 10.0.19015.4894

*Optional*
- Shader: None
- Other Mods:
![Screenshot_116](https://github.com/user-attachments/assets/8da4ec1f-ab10-4f75-81d3-2cd3467bcf1b)

### Additional context
> Add any other context about the problem here.
https://mclo.gs/Sol7Vcy

**Comment by Qendolin** [comment]
This might because of the Fog mod, it's not quite compatible yet.

**Comment by An0therOne** [comment]
is it ever going to be compatible in the future, or?

**Comment by Qendolin** [comment]
Yeah probably

**Comment by Qendolin** [comment]
This should be fixed with
https://modrinth.com/mod/better-clouds/version/1.8.0+1.21.3-fabric-b

I'll port it to older versions if no issues are reported after a while.

**Comment by IMB11** [comment]
Would it be possible to port this fix to 1.20.1 and 1.21? These are the main versions players using https://modrinth.com/mod/fog keep encountering this. I get quite a few bug reports about "Better Clouds" compatability when ultimately it's just this issue :)

**Comment by IMB11** [comment]
Ah missed a few comments, thanks for adding support!

**Comment by IMB11** [comment]
I can test if needed

**Comment by Qendolin** [comment]
I've just published the new update for all supported versions. From my testing there aren't any issues, but my testing wasn't exhaustive.
