### ISSUE TITLE
Crashing when i open the world 

### ISSUE THREAD

**Issue by SamuelKupec** [Qendolin/better-clouds#15]

**Comment by Qendolin** [comment]
Sorry, but you'll have to at least attach the game log. Otherwise I cannot investigate the issue.

**Comment by SamuelKupec** [comment]
> Sorry, but you'll have to at least attach the game log. Otherwise I cannot investigate the issue.

Yeah

**Comment by Qendolin** [comment]
So, can you attach a game log? If you don't I'm just gonna close this issue.

**Comment by Qendolin** [comment]
Bruh
