### ISSUE TITLE
Clouds look like this in 1.21.1 - M1 Mac

### ISSUE THREAD

**Issue by FunkyMonk2003** [Qendolin/better-clouds#152]
Tried messing around in the config, but nothing changed this. Looked and worked perfectly fine in prior versions, with the same mods I used then and now.
<img width="1440" alt="Screenshot 2024-10-08 at 14 28 12" src="https://github.com/user-attachments/assets/e5d3e612-671d-44a4-a64c-564f61bbe0d0">

**Comment by Qendolin** [comment]
Have you tried resetting the config? (by holding shift in the config menu and clicking the reset button in the bottom left).
Can you attach your log?

**Comment by FunkyMonk2003** [comment]
Shift resetting seems to have fixed the issue.
Here's my log either way:
[latest.log](https://github.com/user-attachments/files/17293583/latest.log)

Thanks for the help!
