### ISSUE TITLE
Incorrect dark clouds at night time

### ISSUE THREAD

**Issue by abdmoh123** [Qendolin/better-clouds#153]
## Describe the bug

After release 1.3.17, (1.3.18 and onwards) clouds become unnaturally dark at night time.

> [!Important]
> The clouds still look normal at daytime

## To Reproduce

1. Install any version of better clouds after 1.3.17 (1.3.18-1.3.22) on Minecraft 1.20.1 (fabric)
2. Run /time set midnight
3. Look at how dark the clouds are

### Expected behavior

Should look naturally white, like in the screenshots found in the mod's page (modrinth/curseforge)

#### Before

![2024-10-11_00 44 26](https://github.com/user-attachments/assets/69343f63-33cb-4e44-8909-05f55302c90c)

#### After

![2024-10-11_00 45 26](https://github.com/user-attachments/assets/360ab514-1505-45aa-87b6-558411382686)

**Proof that clouds should be there**

![2024-10-11_00 45 34](https://github.com/user-attachments/assets/2606f1b7-1ef7-4d7a-bf9a-4f3b96d7d3b0)

### System Environment
- GPU: RTX 3070
- Mod Version: 1.3.18-1.3.22 (1.20.1)
- OS: Windows 11

*Optional*
- Shader: No shader
- Other Mods: No other mods other than better clouds dependencies

**Comment by Qendolin** [comment]
You're right, it is too dark. I'll update the brightness calculation to be more dynamic and not as dark at night.

**Comment by Qendolin** [comment]
I think i'll make the brightness dependent on the moon phase. I'm not sure if I'll keep the fully dark clouds at new moon.
![image](https://github.com/user-attachments/assets/2dd0a5c0-01c7-4f00-97e7-3e6149e9500c)
![image](https://github.com/user-attachments/assets/35fa486a-9789-4b4d-9ae3-6aba23f4b910)
![image](https://github.com/user-attachments/assets/45243928-bd53-4788-9ef7-2f438b1a8bcf)
![image](https://github.com/user-attachments/assets/86234238-4ac8-4b0b-89a7-4ed7744d763a)
![image](https://github.com/user-attachments/assets/1b8d12af-2291-4493-b937-4c2c2f87be87)

**Comment by Qendolin** [comment]
This is fixed in this beta version:
https://modrinth.com/mod/better-clouds/version/1.8.0+1.21.3-fabric-b

I'll port it to older versions if no issues are reported after a while.
