### ISSUE TITLE
Clouds are opaque.

### ISSUE THREAD

**Issue by Common-Architect** [Qendolin/better-clouds#154]
## Describe the bug
The clouds are completely opaque in fabric 1.21.1. I have the settings at 50% opacity though.

## To Reproduce
1. It is opaque by default

### Expected behavior
Either an error in the code, or it's not compatible with a texture pack/mod.

### System Environment
- GPU: I don't remember my GPU.
- Mod Version: 1.7.4 (1.21.1)
- OS: MacOS

### Additional context
> Add any other context about the problem here.

**Comment by Qendolin** [comment]
Can you attach your `config/betterclouds-v1.json` file?

**Comment by Qendolin** [comment]
No response
