### ISSUE TITLE
Clouds totally flat

### ISSUE THREAD

**Issue by MrDonut73** [Qendolin/better-clouds#155]
The cloud height suddenly stopped working, and instead reverse changes width and height for example:
![2024-10-17_09 56 38](https://github.com/user-attachments/assets/648a23a5-4560-4e61-9811-741f0ff103cb)
![2024-10-17_09 56 44](https://github.com/user-attachments/assets/92e7a180-809f-4ecc-b1a8-070d712074a5)

**Comment by Qendolin** [comment]
In the normal video settings, make sure clouds are set to Fancy, not Fast.
