### ISSUE TITLE
my minecraft gives some gliches

### ISSUE THREAD

**Issue by EVILOSSE** [Qendolin/better-clouds#156]
The game starts showing strange pink blurs only when I turn on the clouds. I tried changing the settings but it didn't work.
![2024-10-18_14 07 17](https://github.com/user-attachments/assets/c9a1f6f0-90ec-41d6-afd4-e0bb7846d064)
im using 
intel 2020m dual core cpu with his own gpu
4gb ram 
and windows 7
any help ???

**Comment by Qendolin** [comment]
Similar issues have been reported before, but I haven't been able to figure out what causes it. Can you attach your latest.log after the issue occurs?

**Comment by EVILOSSE** [comment]
> Similar issues have been reported before, but I haven't been able to figure out what causes it. Can you attach your latest.log after the issue occurs

what latest.log can i find it in the minecraft files

**Comment by Qendolin** [comment]
Yes, it should be in the Minecraft directory or under `logs/`

**Comment by EVILOSSE** [comment]
> Yes, it should be in the Minecraft directory or under `logs/`

this one ????
[latest.log](https://github.com/user-attachments/files/17445343/latest.log)

**Comment by Qendolin** [comment]
Yeah that's an issue with the Intel HD graphics driver, there is nothing I can do.

**Comment by EVILOSSE** [comment]
> Yeah that's an issue with the Intel HD graphics driver, there is nothing I can do.

ok thx bro
