### ISSUE TITLE
Cloud color setting: "Match fog color"

### ISSUE THREAD

**Issue by Firch** [Qendolin/better-clouds#157]
**Is your feature request related to a problem? Please describe.**
Clouds always have that weird white color that sometimes doesn't fit the biome. It is changeable, but it is impossible to make a color that'd suit all the biomes.

**Describe the solution you'd like**
A solution that would be a config option to use the current fog color instead of using a static HEX color. Enabling that option would make so the color/tint of the clouds always matches the fog color. Especially relevant for Polytone users.

**Describe alternatives you've considered**
Juggling around with the color manually while traveling isn't cool for obvious reasons.

**Comment by Qendolin** [comment]
![image](https://github.com/user-attachments/assets/c424642e-9264-479d-8750-9fac974b9311)
![image](https://github.com/user-attachments/assets/f562e0e5-e3be-40f2-a39a-4e5ceb077c7b)
![image](https://github.com/user-attachments/assets/5466cb3a-ff7c-463c-a825-cb6fb963905b)
How's that?

**Comment by Firch** [comment]
Yeah, something like that, awesome!

Not sure about them being brighter than the fog (that makes sense I guess), but that works for me!

**Comment by Qendolin** [comment]
I'm not sure about the brightness either. But I when the clouds match the fog color too closely it looks quite odd. I might still change it.

**Comment by Firch** [comment]
I think most of the time (by my own observations) the fog color is brighter than the sky color. I see what you mean though, and yeah, would probably look wacky with the darker fog colors like the ones provided as an example.

**Comment by Qendolin** [comment]
You can try out the new color calculation here:
https://modrinth.com/mod/better-clouds/version/1.8.0+1.21.3-fabric-b

I'll port it to older versions if no issues are reported after a while.
