### ISSUE TITLE
Incompatibility with Immersive Portals (1.21.1)

### ISSUE THREAD

**Issue by FW-Gamer** [Qendolin/better-clouds#158]
![381156051-72fde884-32b0-4dbe-98c3-f338055c45d8](https://github.com/user-attachments/assets/3217253b-d8aa-4e4e-ad99-7d9729b889a7)

The clouds do not render properly when a portal shows the overworld

![381156722-c7617168-b0fa-4f90-989b-e04aae3132a1](https://github.com/user-attachments/assets/4b6bfe77-103b-40c0-8d4f-0fa89488524b)

The clouds do not render at all when you look into the overworld from a portal in the nether

![381157362-584d3851-7ece-4b6c-85b1-2cefe7640633](https://github.com/user-attachments/assets/32d9416a-c50a-40a7-ab6b-4487c65766fd)

When you look from the over world trough a nether portal that lets you look trough another portal in the nether it will render the nether and stop rendering the overworld. (might be some other incompatibility I don't really know)

![381162795-b15de85d-3945-42da-9df1-d1fcf4006319](https://github.com/user-attachments/assets/efe47f02-8718-44df-832f-022951b058f6)

Turning on shaders partially fixes the issue but the clouds still don't render trough a portal if you can see the sky and they become jittery and shake arround.

![381166902-c4eb9a2a-e692-4828-949b-b8aa54f2e90c](https://github.com/user-attachments/assets/d0c80cca-5fa0-4bb3-ba37-9de81d6dba71)

Last example but with shaders disabled

Betterclouds version is 1.7.4
Iportals version is 6.0.3
Minecraft 1.21.1

**Comment by Qendolin** [comment]
Since I cannot fix this issue I'll add immersive portals to the incompatible mods list

**Comment by Qendolin** [comment]
Fixed (by listing as incompatible) for future version
