### ISSUE TITLE
Crash with exit code 1 on 1.21.3

### ISSUE THREAD

**Issue by vinnyg0621** [Qendolin/better-clouds#159]
## Description
> Provide a short description of the error
maybe the mod isn't compatible yet with 1.21.3?

### System Environment
- GPU: nVidia GeForce RTX 3060
- Mod Version: 1.7.4+1.21
- OS: Windows 11

*Optional:*
- Shader Pack: 
- Other Mods: 
_N/A_

### Game Log / Crash Report
[latest.log](https://github.com/user-attachments/files/17611955/latest.log)

**Comment by Qendolin** [comment]
Yes, 1.21.3 is not supported

**Comment by vinnyg0621** [comment]
wait you are gonna support 1.21.3 one day if it’s the latest MC version right?

**Comment by Qendolin** [comment]
I currently don't have plans to. Updating to every minor release is very tedious.
