### ISSUE TITLE
[CRASH] Incompatibility with More Nemo's Woodcutter Variants

### ISSUE THREAD

**Issue by heide-oficial** [Qendolin/better-clouds#160]
## Description
> The games doesn't launch, it just crashes. Looks like it is incompatible with [Nemo's Woodcutter](https://modrinth.com/mod/nemos-woodcutter) and/or [More Nemo's Woodcutter Variants](https://modrinth.com/mod/more-nemos-woodcutter-variants).

### System Environment
- GPU: RX 5500 XT 4GB
- Mod Version: 1.7.4+1.21-fabric-r
- OS: Windows 11 Pro

*Optional:*
- Shader Pack: Not using
- Other Mods: A LOT!

### Game Log / Crash Report
> 
[crash.txt](https://github.com/user-attachments/files/17671225/crash.txt)

**Comment by Qendolin** [comment]
Which Minecraft version are you playing? Also, can you upload the full log? This crash is very curious.

**Comment by heide-oficial** [comment]
Oh, my bad for not sending the full log. I'm playing on Minecraft 1.21 release. And indeed, this is a very curious crash, I would never imagine a cloud enhancing mod crashing with a Woodcutter mod LOL
[log.txt](https://github.com/user-attachments/files/17678149/log.txt)

**Comment by Qendolin** [comment]
It seems like More Nemo's Woodcutter Variants is solely at fault here, because in the log that you just sent me better-clouds wasn't mentioned in the cause. Instead another mod `com.axalotl.async` was blamed. To me it seems like the crash in incorrectly attributed to other mods, which might change with each launch. I'll ask on the fabric discord for more info.

**Comment by heide-oficial** [comment]
Thanks! I'll reach More Nemo's Woodcutter Variants issues on Github as well!

PS: I forgot this modpack was with [Async ](https://modrinth.com/mod/async) mod, as I don't actually use this mod because of some incompatibilities, but still, the crash continues without it.

PS²: the game launches normally with only Nemo's Woodcutter, but not with More Nemo's Woodcutter Variants, so the compatibility issue is indeed on the more variants mod.

PS³: here's a crash log without Async mod:
[crash.txt](https://github.com/user-attachments/files/17678839/crash.txt)

**Comment by Qendolin** [comment]
I just asked on the fabric discord. Nemo's Woodcutter Variants has an error, which gets attributed to whichever mod is loaded first. Please open an issue on their github.

**Comment by heide-oficial** [comment]
Just did that. Thanks for the reply and the awesome mod!

Nemo's More Woodcutter Variants issue thread: https://github.com/pnk2u/More-NemosWoodcutter-Variants/issues/2

EDIT: fixed in Nemo's More Woodcutter Variants version 1.1.2: (Fix Mix.in declaration from version 1.1.1 preventing the game from starting in 1.20.0/1.21.1 - 1.21.2/3 was not affected).
