### ISSUE TITLE
1.21.3 please <3

### ISSUE THREAD

**Issue by madeline0706** [Qendolin/better-clouds#163]
I love you

**Comment by Qendolin** [comment]
There have been significant changes in 1.21.3 (code wise) which make updating difficult

**Comment by madeline0706** [comment]
> There have been significant changes in 1.21.3 (code wise) which make updating difficult

Any luck?

**Comment by Qendolin** [comment]
https://modrinth.com/mod/better-clouds/version/1.8.0+1.21.3-fabric-b
