### ISSUE TITLE
blackListedBiomes keeps resetting

### ISSUE THREAD

**Issue by tokiponaenjoyer** [Qendolin/better-clouds#164]
## Describe the bug
> A clear and concise description of what the bug is

blackListedBiomes keeps resetting back to "blackListedBiomes = ["minecraft:the_end"]" no matter what changes I make to it, even when the game is closed and I save it.

## To Reproduce
> Steps to reproduce the behavior

1. Change blackListedBiomes 
2. See change disappear

### Expected behavior
> A clear and concise description of what you expected to happen.

I expected it to add to the config, then I just restart the game and the changes are loaded.

### System Environment
- GPU: AMD Radeon RX 6600
- Mod Version: 1.1 - 1.20.1
- OS: Windows 11

*Optional*
- Other Mods: Create: Northstar (The mod i'm removing clouds from)

**Comment by tokiponaenjoyer** [comment]
by the way this is on forge 47.3.0

**Comment by tokiponaenjoyer** [comment]
my bad, didn't mean to close it

**Comment by Qendolin** [comment]
Are you sure you're reporting this to the right mod? Better Clouds doesn't have a config option `blackListedBiomes`.

**Comment by tokiponaenjoyer** [comment]
> Are you sure you're reporting this to the right mod? Better Clouds doesn't have a config option `blackListedBiomes`.

well it's in my config for some reason, and yes this is the right clouds mod.
![What](https://github.com/user-attachments/assets/80ecb090-f5b6-4316-8f49-7fb5fbaa1e37)

**Comment by Qendolin** [comment]
That config file is from another mod, I don't know which. This mod's config file is `betterclouds-v1.json`.

**Comment by tokiponaenjoyer** [comment]
> That config file is from another mod, I don't know which. This mod's config file is `betterclouds-v1.json`.

that config file literally does not exist, also just in case, I'm talking about this mod: [Better Clouds Reforged](https://www.curseforge.com/minecraft/mc-mods/better-clouds-reforged)

**Comment by Qendolin** [comment]
Well, then you're in the wrong repository. "Better Clouds Reforged" was created by someone back when "Better Clouds" only supported fabric. Issues with BC: Reforged should be reported [here](https://github.com/falling-colud/Better-Clouds-Reforged). Sorry for the confusion.
