### ISSUE TITLE
Celestial Body Halo visual bug with View Bobbing enabled (Beta 1.8.0)

### ISSUE THREAD

**Issue by deathwing1423** [Qendolin/better-clouds#165]
The Celestial Body Halo moves around quite a bit with view bobbing enabled. The effect is completely still with view bobbing disabled. 

https://github.com/user-attachments/assets/33a82313-dc65-40b9-a7dd-7e2455655e9f

**Comment by Qendolin** [comment]
Thanks for reporting, I don't know how that bug keeps coming back 😩

**Comment by Qendolin** [comment]
Fixed https://modrinth.com/mod/better-clouds/version/1.8.1+1.21.3-fabric-b
