### ISSUE TITLE
No Clouds appear since installing the mod

### ISSUE THREAD

**Issue by Infinity028** [Qendolin/better-clouds#166]
I've installed Better Clouds along with YetAnotherConfigLib (as minecraft crashed and asked me to install it for the mod to work) and now there aren't clouds anymore.

The mods I have installed as well are:
Fabric api, iris, modmenu, sodium and sodium extra.

However, if i enable shaders such as Complementary Reimagined the clouds reappear but in the style of the shader, not better clouds
have i done something wrong lol please help

**Comment by Qendolin** [comment]
Make sure you have clouds enabled in the video settings and your render distance is greater than 4. You can also reset all Better Clouds settings by holding Shift in the settings menu and pressing the "Reset" button.
If that doesn't fix the issue then please share your game log (latest.log) and a screenshot of the F3 menu.

**Comment by Infinity028** [comment]
[latest.log](https://github.com/user-attachments/files/18136572/latest.log)
![2024-12-14_16 08 13](https://github.com/user-attachments/assets/5495656f-4007-4af5-a02f-8ef661c8e4b6)

**Comment by Qendolin** [comment]
If you switch back to vanilla in the Better Clouds mod settings, do you see them then?
I could also be a problem with version incompatibility. I haven't really tested 1.21.4.

**Comment by Infinity028** [comment]
I haven't touched any of the settings and everything that can be default is default

**Comment by Its2Factor** [comment]
I'm having the same issue. I'm in a world, and with all the default settings for 1.21.4 - Fabric - Better Clouds, there are no clouds, even when I put the cloud setting to "vanilla".
![image](https://github.com/user-attachments/assets/22b63d06-a3fc-4735-96bb-e2997318ac2f)

**Comment by Infinity028** [comment]
Dude i think i found the problem
I was flicking through every single setting and in the video settings, there's a setting called Multi Dimension fog under render (this is with sodium installed) which was toggled off, and if toggled on, the clouds appear again, even with and without better clouds mod installed

**Comment by Qendolin** [comment]
I can't recreate the issue using the latest sodium and sodium extras version for 1.21.4. If somebody could upload their mods and config folder as a zip file of an instance where it is not working, that would be great.

**Comment by Qendolin** [comment]
Nevermind, I think I just found the issue. The clouds disappear when the fog is set to "OFF"

**Comment by Infinity028** [comment]
I think maybe it’s toggled off by default? It could be worth mentioning that It needs to be toggled on for the mod to work

**Comment by Qendolin** [comment]
I don't think it is OFF by default, but I'll quickly update the mod to fix the issue.

**Comment by Qendolin** [comment]
Yeah that's kinda an issue with Sodium Extras. I hope they change their implementation, but from what I've read I think they want to keep it.

https://github.com/FlashyReese/sodium-extra-fabric/issues/366
https://github.com/FlashyReese/sodium-extra-fabric/issues/393
https://github.com/FlashyReese/sodium-extra-fabric/issues/365

**Comment by Infinity028** [comment]
oh ok, so without sodium extra it should work?

**Comment by Qendolin** [comment]
You just need to set the fog distance in Video Settings > Render to a different value than "OFF" for now. But I'll release a proper fix.

**Comment by Infinity028** [comment]
ok thanks
