### ISSUE TITLE
Not Detecting Fabric Install

### ISSUE THREAD

**Issue by CivilF11** [Qendolin/better-clouds#168]
## Description
I have installed fabric, and I know the fabric install works, since I am using other mods that are fabric-based, and they work fine. Upon launch, this mod throws the error:

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Install fabric, any version.
More details:
	 - Mod 'Better Clouds' (betterclouds) 1.8.2+1.21.4-fabric requires any version of fabric, which is missing!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

I have also removed all the mods except for the required YACL and ModMenu, with the same error.

### System Environment
- GPU: NVIDIA GTX 1080TI
- Mod Version: Release 1.8.2 for 1.21.4 Fabric (1.8.2+1.21.4-fabric-r)
- OS: Windows 10 Education

*Optional:*
- Shader Pack: None
- Other Mods: 
   - cloth-config-17.0.144-fabric
   - modmenu-13.0.0-beta.1
   - simplefog-1.7.0
   - sodium-fabric-0.6.3+mc1.21.4
   - YetAnotherConfigLib-3.6.2+1.21.4-fabric

### Game Log / Crash Report
> Add a link to your game log / crash report or attach it as a file
> If you **do not** attach a log, I will not be able to help you

[latest.log](https://github.com/user-attachments/files/18168745/latest.log)

**Comment by Qendolin** [comment]
"Install fabric, any version." refers to "Fabric API" which is it's own mod, just the error message is misleading. It's a required dependency for a lot of mods. You can download it here: https://modrinth.com/mod/fabric-api/versions

**Comment by CivilF11** [comment]
Oh, I am so sorry! Thank you for getting back to me so quick. Had no idea it was it's own thing :)
