### ISSUE TITLE
crash with new update / mixin calls from sodium extra for fog

### ISSUE THREAD

**Issue by shinycolororange** [Qendolin/better-clouds#169]
1.21.1 fabric, 1.7.5 mod version
here is the full report: https://mclo.gs/KMcFYI4

**Comment by Qendolin** [comment]
Looks like I messed up. Now it won't launch if sodium extra (no -s) is not installed. I'll delete those versions and release another update.

**Comment by Qendolin** [comment]
I've published a fixed version (Should be fixed)
