### ISSUE TITLE
Game crashen when world loads

### ISSUE THREAD

**Issue by TheCrystCreeper** [Qendolin/better-clouds#18]
A few notes:
I am running minecraft on a Steam Deck and only have better clouds and its requirements installed 

Log: https://mclo.gs/NcaLbdU

**Comment by Qendolin** [comment]
Should be fixed in the upcoming version

**Comment by Qendolin** [comment]
Should be fixed now: https://modrinth.com/mod/better-clouds/version/1.1.3+1.19.4-B

**Comment by Qendolin** [comment]
If if is not fixed, comment and I will reopen this issue

**Comment by Qendolin** [comment]
Also, the full release is ready: https://modrinth.com/mod/better-clouds/version/1.2.0+1.19.4-R
