### ISSUE TITLE
Incompatibility with Xaero's World Map + Mini Map

### ISSUE THREAD

**Issue by egeesin** [Qendolin/better-clouds#2]
[latest.log](https://paste.ee/p/mTKeg)

When Better Clouds with Xaero's mods are enabled, there's a problem with checkpoint location as seen in the video below. 
[![Incompatibility with Xaero's World Map + Mini Map](http://img.youtube.com/vi/pfKH0EZr_V4/0.jpg)](http://www.youtube.com/watch?v=pfKH0EZr_V4 "Click to play the video.")

**Comment by Qendolin** [comment]
I'm gonna guess it's because of OpenGL state. Such a pain... I'll have a look

**Comment by Qendolin** [comment]
I was just missing a push and pop.

**Comment by Qendolin** [comment]
Fixed https://modrinth.com/mod/better-clouds/version/f4jg6EtK
