### ISSUE TITLE
Clouds only render when shaders are enabled

### ISSUE THREAD

**Issue by Spittys** [Qendolin/better-clouds#27]
I have enabled the "always render" and tried my best, however the clouds just won't render on shaderless. they render beautifully with shaders, but won't render at all without them

**Comment by Qendolin** [comment]
That sounds bad 🫤
Can you share your game log?

**Comment by Spittys** [comment]
Just entered a world, set the style from vanilla to better clouds, and left.
[latest.log](https://github.com/Qendolin/better-clouds/files/11821833/latest.log)

**Comment by Spittys** [comment]
Just entered a world with only the mod, YACL, and QFAPI and it works fine. Definitely an incompatibility issue then. I'll try to find out the mod causing the issue

**Comment by Spittys** [comment]
I found it. It's immersive portals, no clue why. I'm gonna close this issue and start a new one about the incompatibility.
