### ISSUE TITLE
Visual error: Static noise when using mod

### ISSUE THREAD

**Issue by KB-Q** [Qendolin/better-clouds#29]
## Description
Some sort of static noise covers the screen.
![2023-06-25_15 02 22](https://github.com/Qendolin/better-clouds/assets/59303688/394e6fbb-0839-4cf6-9133-f5db2a5acf60)

### System Environment
- GPU: Intel Integrated graphics
- Mod Version: 1.2.1+1.19.4
- OS: Windows 11

*Optional:*
- Shader Pack: None
- Other Mods: https://paste.ee/p/7h7tj

**Comment by Qendolin** [comment]
Can you attach your game's log?

**Comment by KB-Q** [comment]
The latest.log seems to have changed unfortunately, as I removed the mod and played for a while today as well
And Idk how to recover previous sessions' logs

**Comment by Qendolin** [comment]
Sorry, but in this case I don't think I'll be able to investigate this issue.

**Comment by Qendolin** [comment]
Should be fixed: https://modrinth.com/mod/better-clouds/version/1.3.2+1.20.1-B
