### ISSUE TITLE
1.20.1 Screen Noise Issue

### ISSUE THREAD

**Issue by reisscake** [Qendolin/better-clouds#31]
Upon using the mod and loading into any world I get greeted with this: 

![image](https://github.com/Qendolin/better-clouds/assets/102161059/4529a64a-0877-401a-8bd1-49f54ad25191)

log file: https://paste.ee/p/UJlvB

If it makes it more useful, id love to provide a log file without the other mods I have and just this one?

**Comment by Qendolin** [comment]
The new version which you are using includes a new (experimental) command `/betterclouds:debug trace` which collects some debugging information and stores it in a zip file. The command may crash you game and its not fully done but it might provide me with some more insight on whats causing this issue. Can you run it and upload the resulting zip file?

**Comment by reisscake** [comment]
[debug-trace-2023-06-28_165501.zip](https://github.com/Qendolin/better-clouds/files/11896211/debug-trace-2023-06-28_165501.zip)

this is what i got on my end :)

**Comment by reisscake** [comment]
i can confirm that it does work, thank you :)

**Comment by Qendolin** [comment]
Published: https://modrinth.com/mod/better-clouds/version/1.3.2+1.20.1-B
