### ISSUE TITLE
Random crash whilst trying to go multiplayer

### ISSUE THREAD

**Issue by Taiyou06** [Qendolin/better-clouds#32]
## Description
Happens everytime i try to log in my server. No clue what it is.

### System Environment
- GPU: RTX 2060
- Mod Version: 1.2.3
- OS: Windows 10

*Optional:*
- Other Mods: 
![image](https://github.com/Qendolin/better-clouds/assets/77050201/56c73141-4080-46a8-b19b-2fdd6f0e4ff6)
![image](https://github.com/Qendolin/better-clouds/assets/77050201/a83537cb-44ea-4231-97d4-784980d51cee)

### Game Log / Crash Report
https://mclo.gs/8BbVRDy

**Comment by Qendolin** [comment]
Looks like I broke something in the latest release 😅

**Comment by Taiyou06** [comment]
yeah looks like 😅

**Comment by Qendolin** [comment]
Can you send the file `hs_err_pid5024.log`, it should be in `%APPDATA%\PrismLauncher\instances\Gensokyo Reloaded QOL\.minecraft\`

**Comment by Taiyou06** [comment]
[hs_err_pid5024.log](https://github.com/Qendolin/better-clouds/files/11899044/hs_err_pid5024.log)

**Comment by Qendolin** [comment]
Thanks, fixed version is here: https://modrinth.com/mod/better-clouds/version/1.2.4+1.19.4-R

**Comment by Taiyou06** [comment]
uhhhh it still crashed..?
https://mclo.gs/Xk5hXNa
[hs_err_pid6428.log](https://github.com/Qendolin/better-clouds/files/11899057/hs_err_pid6428.log)

**Comment by Qendolin** [comment]
There must be another error then, I'll check it out

**Comment by Qendolin** [comment]
Does it only crash when joining the server or also in singleplayer?

**Comment by Taiyou06** [comment]
> Does it only crash when joining the server or also in singleplayer?

was afk sorry, lemme check

**Comment by Taiyou06** [comment]
yeah singplayer is fine

**Comment by Taiyou06** [comment]
okay so i think my resourcepack in my server causes the crash
[test.zip](https://github.com/Qendolin/better-clouds/files/11900549/test.zip)
see if it crashes on ur end as well

**Comment by Qendolin** [comment]
I've downloaded all of the mods and loaded the resource pack but it's not crashing for me. Maybe something on the server is triggering the issue?

**Comment by Taiyou06** [comment]
> I've downloaded all of the mods and loaded the resource pack but it's not crashing for me. Maybe something on the server is triggering the issue?

add me on discord if you want to (taiyouh) i can send you the ip (whitelisted server) and check if it happens or not on your end too

**Comment by Qendolin** [comment]
After some more testing the issue didn't occur again
