### ISSUE TITLE
Clouds are still rendered after triggering the darkness effect

### ISSUE THREAD

**Issue by aotusoft** [Qendolin/better-clouds#36]
![2023-07-09](https://github.com/Qendolin/better-clouds/assets/51018049/c7ddcab3-aa92-41f5-91f6-20ddf522bc28)

**Comment by Qendolin** [comment]
This should be an easy fix but it really isn't. So far I haven't been able to come up with a good solution. I might publish a bodged solution if it takes too much time to fix it properly

**Comment by aotusoft** [comment]
> This should be an easy fix but it really isn't. So far I haven't been able to come up with a good solution. I might publish a bodged solution if it takes too much time to fix it properly

thanks so much!

**Comment by Qendolin** [comment]
Should be fixed https://modrinth.com/mod/better-clouds/version/1.3.6+1.20.1-R

**Comment by aotusoft** [comment]
oh thanks
