### ISSUE TITLE
Clouds disappear when settings graphics quality to "Fabulous!"

### ISSUE THREAD

**Issue by fennecr** [Qendolin/better-clouds#37]
## Describe the bug
When setting the graphical quality to Fabulous, the clouds stop rendering.

## To Reproduce

1. Set graphics to fabulous with betterclouds enabled.

### Expected behavior
Clouds continue rendering regardless.

### System Environment
- GPU: NVIDIA 1060 6GB
- Mod Version: 1.3.5 for 1.20.1
- OS: Windows 10

*Optional*
- Shader: None
- Other Mods: Sodium

**Comment by Qendolin** [comment]
I'll release the fix when I also fix https://github.com/Qendolin/better-clouds/issues/36 , meanwhile you can just use fancy Graphics since Fabulous has a barely noticeable improvement over Fancy

**Comment by Qendolin** [comment]
Should be fixed https://modrinth.com/mod/better-clouds/version/1.3.6+1.20.1-R
