### ISSUE TITLE
After breaking blocks, sometimes clouds render in front of blocks

### ISSUE THREAD

**Issue by AeiouEnigma** [Qendolin/better-clouds#4]
This is a bizarre, inconsistent issue that's a bit annoying to reproduce, and which only lasts for a split second. Often, after breaking blocks (especially in an enclosed space with torches), the cloud layer will render even when it should be completely obstructed by blocks. This is really jarring and frankly freaked me out the first time I saw it. Reproducible using only Better Clouds, Fabric API, and mod menu.

I'm able to reproduce the issue fairly reliably by making an enclosed underground space and just placing/breaking a bunch of torches and other blocks.

Screenshots of issue:

![image](https://user-images.githubusercontent.com/3160746/148114258-4ccb3d52-4067-42a3-afc6-69003edf08f1.png)

![2022-01-04_14 43 05_2](https://user-images.githubusercontent.com/3160746/148115107-2830b35d-4cf8-4ff6-8f29-a6cb0742accb.png)

**Comment by Qendolin** [comment]
Can confirm, but it doesn't happen when breaking blocks but when picking up items, very strange.

**Comment by AeiouEnigma** [comment]
The second screenshot was from Creative testing, when I was definitely not picking up any items, so there may be multiple causes.

**Comment by Qendolin** [comment]
Are you sure? I can see you have 28 torches.

**Comment by AeiouEnigma** [comment]
...........You may have a point. I hadn't considered the torches that would've fallen from me breaking the stone blocks.

**Comment by AeiouEnigma** [comment]
That's a *weird* issue.

**Comment by Qendolin** [comment]
Mojangs code is so messy, no wonder they have so many bugs. Something somewhere when picking up items disables the depth test and doesn't enable it again.

**Comment by Qendolin** [comment]
Fixed https://modrinth.com/mod/better-clouds/version/f4jg6EtK

**Comment by AeiouEnigma** [comment]
I've confirmed that actually this issue still occurs 😭

**Comment by Qendolin** [comment]
How 😶? The issue when picking up items is definitely fixed, gotta be something else...

**Comment by Qendolin** [comment]
Sorry, I can't recreate the issue anymore. Are you playing with other mods or different video settings?

**Comment by AeiouEnigma** [comment]
I've reproduced it with only Better Clouds 1.0.3, still by picking up items.

If you're certain you've fixed it, is it possible you uploaded the wrong file?

**Comment by Qendolin** [comment]
I feel so stupid rn, I did upload the wrong file. Even tho for testing I downloaded 1.0.3 from modrinth to make sure everything is ok. But I used my minecraft instance with a bunch of other mods that somehow prevented the bug from occurring. 

This time, download from modrinth and tested in isolation: https://modrinth.com/mod/better-clouds/version/LVrQHf7k
