### ISSUE TITLE
Modrinth version labels are wrong

### ISSUE THREAD

**Issue by xyxt1c** [Qendolin/better-clouds#41]
Just a small thing ;)

On the modrinth page the newer updates have confusing labels.
1.2.7 for 1.19.2 and 1.2.7 for 1.19.4 have the Fabric 1.20-1.20.1 labels, which confuses me and mod updater like prism launcher. Theese labels need to be corrected to prevent automatic downgrades through mod launchers.

![Bildschirmfoto vom 2023-07-12 17-15-56](https://github.com/Qendolin/better-clouds/assets/138204417/a4bb9cce-31d1-44ce-9f79-232fa754e764)

**Comment by Qendolin** [comment]
Should be fixed now, I didn't intend to specify any version of the dependencies at all

**Comment by Qendolin** [comment]
Now it is really fixed
