### ISSUE TITLE
Extended clouds with "Extended clouds mod" to work

### ISSUE THREAD

**Issue by Zorklis** [Qendolin/better-clouds#45]
So currently Better Clouds look better than Vanilla ones but clouds are still in the Vanilla area and don't extend that far. Could there be support for "extended clouds" mod or built in option to have more clouds in the distant.
Thanks

**Comment by Qendolin** [comment]
It might not seem that way but the clouds render up to four times farther than the game world, unlike vanilla clouds. There are some ways how I could render them even further out, but it's not trivial and will probably break compatibility with some other mods.

**Comment by Qendolin** [comment]
I'm not closing this issue since I haven't extensively tested this. If anyone can show me an example where Extended Clouds renders at a greater distance than my mod then I will revisit this issue.
