### ISSUE TITLE
the clouds are rippling

### ISSUE THREAD

**Issue by AwesomIceberg** [Qendolin/better-clouds#46]
I tried playing without mods and it doesn't help.
I tried changing the settings of the mod, it doesn't help either.
what is the problem?
![Screenshot_6](https://github.com/Qendolin/better-clouds/assets/143116740/3ccf51a3-5e09-4bfa-b5ed-ab10fb43d8c5)

**Comment by AwesomIceberg** [comment]
[latest.log](https://github.com/Qendolin/better-clouds/files/12433187/latest.log)

**Comment by Qendolin** [comment]
Ok, the log didn't contain any entries that would help me figure out this issue. Can you attach a screenshot of your F3 screen?

**Comment by AwesomIceberg** [comment]
![Screenshot_11](https://github.com/Qendolin/better-clouds/assets/143116740/f789e241-9e7c-4d4f-858d-398491e9c580)

**Comment by AwesomIceberg** [comment]
![Screenshot_27](https://github.com/Qendolin/better-clouds/assets/143116740/09c57e5c-00b1-42b9-a6ec-e2ca1573d63a)

you won't believe it but i just changed the launcher and it worked
