### ISSUE TITLE
"Failed to load config screen"

### ISSUE THREAD

**Issue by piiko** [Qendolin/better-clouds#48]
Just as the title says, the mod doesn't load with a config screen, and mod menu says to report it here. 

The error in mod menu says "Java.lang.RuntimeException: Mixin transformation of dev.isxander.yacl3.gui.AbstractWid get failed". Idk what it means, hope you do :L

If you already know of this issue, sorry that you got another complaint and hope you can fix it soon :)

**Comment by Qendolin** [comment]
HI, please add a log file or I can't help you.

**Comment by piiko** [comment]
![javaw_FjEg0idV4c](https://github.com/Qendolin/better-clouds/assets/51325506/c78ac888-b767-46bd-82e7-9bccc19148e0)

**Comment by Qendolin** [comment]
Should be fixed: https://modrinth.com/mod/better-clouds/version/1.3.9+1.20.1-R

**Comment by piiko** [comment]
It was, big ups dev
