### ISSUE TITLE
Clouds are too bright when using Complementary Shaders

### ISSUE THREAD

**Issue by NathansCodes** [Qendolin/better-clouds#49]
## Describe the bug

As said above, the clouds are very bright and don't adapt to the weather.
I can't seem to change this behaviour, hence this issue.
This problem occurs both on Windows and on Linux with proprietary Nvidia drivers. 

## To Reproduce
> Steps to reproduce the behavior

1.  Install Complementary Shaders
2. clouds are too bright

### Expected behavior

Clouds aren't as bright and their color and opacity adapt to the current weather.

### Screenshots

Expected Result, with `rethinking voxels` shader:
![](https://github.com/Qendolin/better-clouds/assets/99505972/61204ffe-7adf-46c3-9f81-43c17158abb8)
![2023-09-27_18 27 21](https://github.com/Qendolin/better-clouds/assets/99505972/68bec993-98b1-493f-92d2-087223fa159d)

What I get with `Complementary Shaders`:
![2023-09-27_16 27 04](https://github.com/Qendolin/better-clouds/assets/99505972/dfe53999-c30f-4e1f-a116-38589483baa7)
![2023-09-27_18 26 43](https://github.com/Qendolin/better-clouds/assets/99505972/9c4aeaa0-c9b7-4bef-89c5-36a089d10abe)

For reference some shots without any shaders:
![2023-09-27_16 28 45](https://github.com/Qendolin/better-clouds/assets/99505972/8406217b-fe77-4aaf-93fe-e08f3ee090e5)
![2023-09-27_17 55 35](https://github.com/Qendolin/better-clouds/assets/99505972/8a3e1d57-03c3-4883-9aef-9ce1965db656)

### System Environment
- GPU: GTX 1650
- Mod Version: 1.3.8

**Comment by Secret-chest** [comment]
Lower the opacity.

**Comment by Qendolin** [comment]
There are a lot of settings available, if you find settings that look better you can upload you config and I may set it as the default.

**Comment by Qendolin** [comment]
Btw, thank you for actually filling out the issue template

**Comment by NathansCodes** [comment]
Nevermind, just found out that issue #48 was fixed.
I couldn't set it to the right preset before, but now I can and it works.
Sorry if I wasted your time
