### ISSUE TITLE
You can see the vanilla clouds when you leave the water for a short moment

### ISSUE THREAD

**Issue by JosephG1thub** [Qendolin/better-clouds#50]
Just when you get out of the water you can see the vanilla clouds for a short moment.

Steps:
1. Enter the water
2. Try to get out gently

https://github.com/Qendolin/better-clouds/assets/123671346/883fc1cd-320e-45ba-8573-81de9587307f

**Comment by Qendolin** [comment]
Oh, I know why, should be fixed soon

**Comment by Qendolin** [comment]
Fixed for 1.19.3 - 1.20.2
