### ISSUE TITLE
Crash on start-up when using 1.17.1 version

### ISSUE THREAD

**Issue by Yenlon** [Qendolin/better-clouds#51]
## Description
I can't proceed to the Mojang loading screen due the sudden crash when clicking the play button, instead I get this short crash report I posted down below. It seems to be a java issue which confuses me because I had java 20 installed which is way above the minimum Fabric requires from me. I then deinstalled java 20 and installed java 17 instead but I still get the crash report. I don't know what to do anymore, maybe it's an issue from my side completely as for me everything that has to do with changing java versions properly is a big hassle or maybe it's conflicting with the other mods I installed.

### System Environment
- GPU: 11th Gen Intel(R) Core(TM) i7-11700KF
- Mod Version: 1.17.1
- OS: Windows 11

*Optional:*
- Shader Pack: None
- Other Mods: 
![mods 30 09 2023 20_18_54](https://github.com/Qendolin/better-clouds/assets/67074171/4a193962-a876-4b8c-9781-71e4d7aa583b)

### Game Log / Crash Report
![Fabric Loader 0 14 22 30 09 2023 20_27_46](https://github.com/Qendolin/better-clouds/assets/67074171/61a60c00-4cef-4514-9882-f2aad2b9dad2)

**Comment by Qendolin** [comment]
Simply installing a newer version of java is not enough, you still have to select it in your launcher.

**Comment by Yenlon** [comment]
Oh and how do I do it?

**Comment by Qendolin** [comment]
Depends on which launcher you are using

**Comment by Yenlon** [comment]
I use the standard MC launcher

**Comment by Qendolin** [comment]
Idk, maybe try https://minecrafthopper.net/help/guides/changing-java-version/

**Comment by Qendolin** [comment]
Here, I lowered the version requirement: https://modrinth.com/mod/better-clouds/version/1.0.5+1.17.1
Please note that I will not be fixing any bugs for the 1.17 version

**Comment by Yenlon** [comment]
> Idk, maybe try https://minecrafthopper.net/help/guides/changing-java-version/

It didn't work. I get a java-runtime-incompatibility-error

**Comment by Yenlon** [comment]
> Idk, maybe try https://minecrafthopper.net/help/guides/changing-java-version/

I can't get it to work, I get instead a java runtime incompatibility error before start-up

> Here, I lowered the version requirement: https://modrinth.com/mod/better-clouds/version/1.0.5+1.17.1 Please note that I will not be fixing any bugs for the 1.17 version

Sadly I get the error below. I really appreciate that you tried to help, it's unfortunate that you don't support 1.17.1 anymore. I wish I could change the version of the map I play on but I mustn't change it otherwise everything will break. Well, I will see what I can do later.

![Fabric Loader 0 14 22 01 10 2023 20_06_26](https://github.com/Qendolin/better-clouds/assets/67074171/59a14651-3118-4654-a7b4-cf6ab1959e5c)

**Comment by Yenlon** [comment]
> > Idk, maybe try https://minecrafthopper.net/help/guides/changing-java-version/
> 
> I can't get it to work, I get instead a java runtime incompatibility error before start-up

Nevermind, I researched and found out that I needed to delete JavaCheck.jar. Now MC finally launches perfectly fine with your mod and I can enjoy your clouds in my world :) Thank you for your efforts!
