### ISSUE TITLE
API for modifying cloud and coverage formation speed

### ISSUE THREAD

**Issue by Steveplays28** [Qendolin/better-clouds#52]
**Is your feature request related to a problem? Please describe.**
I'd like to modify the cloud and coverage formation speed from my mod, Realistic Sleep, while players are sleeping.

**Describe the solution you'd like**
It'd be nice to have an API to do this, having a class `api.BetterCloudsApi` containing methods to set the `u_time` uniform would be awesome.

**Describe alternatives you've considered**
Currently I'd have to mix into Better Clouds to change the `u_time` uniform.

**Additional context**
\-

**Comment by Qendolin** [comment]
`u_time` is tied to `WorldRenderer#ticks`, ideally if your code works with vanilla clouds it should work with BetterClouds as well unless I have a bug in my code. If it doesn't work I'ld be interested to find out why.

On a different note, just setting `u_time` wouldn't be enough. The shader doesn't move the the clouds, it gets the transformation from the CPU. Also new clouds need to be generated on the CPU side. So there are multiple systems that depend on `WorldRenderer#ticks`

**Comment by Steveplays28** [comment]
Hi Qendolin, I've spent some more time looking into this. It seems like the WorldRenderer's ticks aren't bound to the world's ticks or I'm doing something wrong.
I tried incrementing the world's time ticks on the server and sending that to all clients, that doesn't seem to have an effect.

**Comment by Qendolin** [comment]
Yes, the `WorldRenderer` as well as some other places (`InGameHud`, `GameRenderer`) have their own internal tick counters, which get incremented when their repective `tick` method is called.

**Comment by Steveplays28** [comment]
Thanks Qendolin, calling `WorldRenderer#tick` works!
I've released a new version of Realistic Sleep with Better Clouds compatibility ([`v1.10.0`](https://modrinth.com/mod/realisticsleep/versions)).

I appreciate the help. I'll close this issue.
