### ISSUE TITLE
Telemetry is incompatible with VulkanMod

### ISSUE THREAD

**Issue by OrigamingWasTaken** [Qendolin/better-clouds#53]
## Description
> Telemetry calls a function, which is unsupported by Vulkan

### System Environment
- GPU: Apple M1 Chip
- Mod Version: 1.3.10
- OS: MacOS

*Optional:*
- Shader Pack: 
- Other Mods: 

### Game Log / Crash Report
> Add a link to your game log / crash report or attach it as a file
> If you **do not** attach a log, I will not be able to help you
https://mclo.gs/Gt5Zaw7

**Comment by Qendolin** [comment]
Thank you for reporting this issue. Sorry that the telemetry caused your game to crash. I gave my best effort to make it trouble free. I'm not sure if the mod will be compatible if I fix this issue, but I'll try.

**Comment by OrigamingWasTaken** [comment]
Thanks 👍

**Comment by Qendolin** [comment]
Sadly the vulkan mod is not mature enough and does not support enough functionality for me to support it.

**Comment by OrigamingWasTaken** [comment]
No problem, thanks for trying

**Comment by Tmpod** [comment]
Apologies for necro'ing on this issue, but could you take a new look at this? The mod has evolved quite significantly since last time, perhaps it is possible now?

Thank you!

**Comment by Qendolin** [comment]
@Tmpod I actually checked it a few weeks ago. These mods are fundamentally incompatible.

**Comment by Tmpod** [comment]
Oh, sad to hear. Thank you anyway!

**Comment by Versatile-V1** [comment]
@Qendolin Is that because vulkanmod completely rewrites the clouds?

**Comment by Qendolin** [comment]
That too, but the main reason is that Better Clouds uses a lot of direct OpenGL calls. And those obviously don't work with Vulkan Mod.
