### ISSUE TITLE
Transformation into a full blown weather improvement mod

### ISSUE THREAD

**Issue by aarizwx** [Qendolin/better-clouds#56]
I can't help but look at these volumetric clouds and wonder what they would look like in a better weather type mod, such as supercell thunderstorms, tornadoes etc. 

Have you considered doing something like this? There is a massive weather community online and within Minecraft who would appreciate a better looking alternative to the weather and tornadoes mod by Corosus, especially since he barely has time to work on it despite it being one of the most popular Minecraft mods of all time, garnering millions of downloads and views on YouTube in its hayday when it was still being updated.

Who will relight that spark?

**Comment by Secret-chest** [comment]
I would like to see a compatible mod. But this one should stay cosmetic.

**Comment by Qendolin** [comment]
While I have plans to bring more variety to the cloud formations I think this suggestion is simply out-of-scope for this mod. That is not something that I can accomplish in my time.
