### ISSUE TITLE
1.20.4 support

### ISSUE THREAD

**Issue by Ev3rgarden** [Qendolin/better-clouds#58]
the moment i found this mod the moment i become my top 5 mod of all time :3 i will make sure to donate the next time i get my check keep the amazing work up!

**Comment by Qendolin** [comment]
I might have time on the weekend

**Comment by Qendolin** [comment]
I don't know why you closed the issue, but here is the update: https://modrinth.com/mod/better-clouds/version/1.5.0+1.20.4-R
