### ISSUE TITLE
Support for HeadInTheClouds.

### ISSUE THREAD

**Issue by MagmaBro123** [Qendolin/better-clouds#59]
Title. See https://modrinth.com/mod/head-in-the-clouds.

If this is dead, please remove it.

**Comment by Qendolin** [comment]
Can you tell me how it is not supported / what do you think should be done differently? I haven't had time to check it out.

**Comment by MagmaBro123** [comment]
BetterClouds also has a height setting. HeadInTheClouds should respect said setting.

**Comment by Qendolin** [comment]
I hope you want it for 1.20.2 or later

**Comment by Qendolin** [comment]
That was a lot more work than I expected it to be: https://modrinth.com/mod/better-clouds/version/1.4.4+1.20.2-R

**Comment by Qendolin** [comment]
If you experience any issues, please open a new issue.
