### ISSUE TITLE
Iris support

### ISSUE THREAD

**Issue by SHsuperCM** [Qendolin/better-clouds#6]
Is it possible to make the clouds show while shaders are active?

For reference I've tried Sildur's Enhanced Default.

**Comment by Qendolin** [comment]
After having a look, this seems quite complicated as it's not an issue with Iris in particular. A shaderpack can decide the cloud rendering mode (off,fancy,fast) and also what to do with the rendered clouds. In the case of Sildurs shaders with Iris the clouds get rendered but the shader decides not to show them. But there seem to be a few issues that I can try to fix.

**Comment by Qendolin** [comment]
I had a chat with some Iris devs on DC and unfortunately I this is basically impossible.

**Comment by SHsuperCM** [comment]
Dang.. Thanks for taking a look at least

**Comment by Qendolin** [comment]
So. I've got this:
![image](https://user-images.githubusercontent.com/32160662/152893335-b5970526-93bb-4247-84ca-56703f01a49d.png)
But I was told that maintaining this will probably be a ton of work.
So don't dismiss the feature completely for now. I *might* add it as an experimental setting soon.

**Comment by Qendolin** [comment]
![image](https://user-images.githubusercontent.com/32160662/152895723-ab7aa12e-8d82-4526-9466-7d97c0134a02.png)
Previous image was BSL, this is Complementary.

**Comment by Qendolin** [comment]
I am reconsidering this

**Comment by Qendolin** [comment]
Experimental support for iris shaders is here. Be sure to enable it in the settings first! From my testing a lot of shaderpacks look great if you fiddle with the settings a little.

**Comment by Qendolin** [comment]
The newest release features config presets for some shaders, if you use a shader that doesn't have a preset yet or you've spotted an issue with a preset please let me know
https://modrinth.com/mod/better-clouds/version/1.1.3+1.19.4-B
