### ISSUE TITLE
Visual bug?

### ISSUE THREAD

**Issue by Dasmin-12** [Qendolin/better-clouds#63]
![2024-01-11_06 46 17](https://github.com/Qendolin/better-clouds/assets/156336707/ef1d8746-7603-43ba-8bf2-4054bc06a40b)
(the trees are cut off)

strange line appearing the colour of the sky. This only happened after I installed this mod. also I'm on a multiplayer server
the thing only appears when I look to a certain direction
its blinking so sometimes its not even there but it certainly keeps coming back. doesn't appear when indoors or inside a cave
might be mod incompatibility or something

**Comment by Qendolin** [comment]
This feels like it's an incompatibility with another mod. Can you attach your game log so that I can check it?

**Comment by Dasmin-12** [comment]
latest.log?
[latest.log](https://github.com/Qendolin/better-clouds/files/13915977/latest.log)

**Comment by BioTechproject27** [comment]
That is a lod of mods..
It would help if you could disable some mods (except better clouds) and try to see with which mod(s) specifically it appears.
Does this also happen with singleplayer worlds?
That would help narrow it down.
