### ISSUE TITLE
Better clouds mod not behaving as anticipated with other (modded) overworld world types

### ISSUE THREAD

**Issue by Neil2250** [Qendolin/better-clouds#65]
**Issue:**  I'm currently using the Ecospherical expansion mod to generate interesting skylands-ish terrain for a project i'm developing, and it appears that the Better Clouds mod does not function in other overworld world types. 

**To replicate:** Acquire the mods noted below, arrive at world creation menu, pick any of the Ecospherical world types in the world type menu, generate world, look up at (lack of) Better Clouds.

Mod list (identical in both images):

* better clouds 1.3.13+1.20.1
* eco-1.20.1-2.2.0
* fabric-api-0.91.0+1.20.1
* iris-mc1.20.1-1.6.11
* modmenu-7.2.2
* sodium-fabric-mc1.20.1-0.5.3
* yet-another-config-lib-fabric-3.2.0+1.20

![World types](https://github.com/Qendolin/better-clouds/assets/156634709/bae69719-c460-4aa1-a023-7d57c3e47db2)

Left image features the "OG_Stratospherical" world type, right image features the default minecraft world type. 

While your mod is working as expected in default circumstances, is there any way to make this mod function in other overworld world types? "SuperFancyClouds: Rearchitected" has this functionality and works as anticipated across different overworld world types, but it does not match the ambiance i'm hoping to achieve with your mod.

**Comment by Neil2250** [comment]
Additional: When the level.dat of the "og_strat." world is replaced with the level.dat of the default world, the mod functions as intended. This is more an observation rather than a solution! _(pre-genning a large portion of terrain then setting up a world border is less than ideal! :) )_
![image](https://github.com/Qendolin/better-clouds/assets/156634709/c5fc9b9e-11a3-4ceb-be85-6f7ffd40986e)

**Comment by Qendolin** [comment]
Thank you for the detailed report, however this seems to be already covered by [#61](https://github.com/Qendolin/better-clouds/issues/61)

**Comment by Neil2250** [comment]
Aha! Well thank you very much. The colour editor sounds exciting! 

If i may ask, when the update that adds this compatibility comes out, will it be available for 1.20.1?

**Comment by Qendolin** [comment]
Very likely
