### ISSUE TITLE
Make growing/shrinking speed configurable

### ISSUE THREAD

**Issue by optionboom** [Qendolin/better-clouds#68]
The speed at which individual cloud boxes change size is too fast for my preferences, it's a little distracting. It would be nice if I could make it considerably slower/gentler.
Apologies if there's already a way to do this, but I couldn't figure it out from the config. I tried adjusting wind speed and didn't notice a difference. Additionally, I'm using this mod on Forge via Sinytra Connector, if this isn't normal behavior.

**Comment by Qendolin** [comment]
I've just released an update for 1.20+ that adds this option ("Wind Speed" in the appearance settings).
