### ISSUE TITLE
Feature: Show realtime preview behind config screen like Iris shader mod.

### ISSUE THREAD

**Issue by BryceBubbles** [Qendolin/better-clouds#7]
It would be really helpful to have the game screen visible when in the config menu.
It seems like Iris just removes the middle menu background, but perhaps it's not that simple? :)

Thanks for developing this mod, it's awesome!

**Comment by Qendolin** [comment]
This is probably gonna happen

**Comment by Qendolin** [comment]
Implemented in [1.0.5](https://modrinth.com/mod/better-clouds/version/1.0.5+1.18.2-R)
