### ISSUE TITLE
Distant Horizons / Better Clouds layering issue

### ISSUE THREAD

**Issue by Neil2250** [Qendolin/better-clouds#70]
## Describe the bug
Seen in image below, Betterclouds is layering in-front of Distant Horizon's terrain. 

## To Reproduce

1. Download Distant Horizons mod for fabric (and dependencies if applicable)
2. Download better clouds mod for fabric (and dependencies if applicable)
3. load up a skylands world, or a tall world, via whatever your chosen world generator is.
4. adjust clouds to intersect with land, any height works. Look around.
5. (seen in image)
...

### Expected behavior
Clouds should always "layer" behind blocks when geographically located behind the blocks- even the "fake" blocks from DistantHorizons. 

### Screenshots

![image](https://github.com/Qendolin/better-clouds/assets/156634709/91be44e4-39a1-43ca-92aa-82aa8b403817)

(Annotated below)

![123](https://github.com/Qendolin/better-clouds/assets/156634709/9c276791-0f17-4ce1-bbda-c34b80d816f4)

### Additional context
Ultimately I believe this is an issue with Distant Horizons, since what they're doing is far more invasive into the game's code than this is, and it may well be fixed by one of their future updates. Not to mention, ultimately, distant horizons is still in beta.

However, I've reported it here just so you're aware that there is an visual incompatibility, even if it's not world-ending.

**Comment by Qendolin** [comment]
Thanks for the detailed report. I am already aware of this issue, and so are the DH Devs. This is something that they need to fix on their end, as far as I am aware. But I guess I'll keep this issue open, so that it doesn't get reported again. 
I haven't looked into it a lot but I might be able to make a workaround.

**Comment by Qendolin** [comment]
Here is the issue on their GitLab:
https://gitlab.com/jeseibel/distant-horizons/-/issues/127
As I understand this issue also happens with vanilla clouds.

I should probably also link their [Ko-Fi](https://ko-fi.com/distanthorizons), in case anyone wants to donate.

**Comment by Qendolin** [comment]
It took my 4 hours, but now the issue is fixed: https://modrinth.com/mod/better-clouds/version/1.3.15+1.20.1-R , it wasn't as difficult as I expected.
1.20.1+ following soon.
