### ISSUE TITLE
Cannot launch Better Clouds 1.4.8 for 1.20.2

### ISSUE THREAD

**Issue by nrsprs** [Qendolin/better-clouds#71]
## Java cannot execute client due to errors in better-clouds
Game crashes on launch, minecraft creates error message linked below. 

## Environment:
* Minecraft java 1.20.2 
* yet-another-config-lib-fabric-3.3.0-beta.1+1.20.2.jar
* fabric-api-0.90.71.20.2.jar
* better-clouds-1.4.8+1.20.2.jar
* macos sonoma 

## Crash Report: 
[crash-2024-02-18_17.08.34-client.txt](https://github.com/Qendolin/better-clouds/files/14324611/crash-2024-02-18_17.08.34-client.txt)

### System Environment
- GPU: AMD Radeon Pro 5500M
- Mod Version: 1.4.8
- OS: macos
- Other Mods: listed

**Comment by Qendolin** [comment]
Ooof, seems I messed up. Gonna fix it now

**Comment by Qendolin** [comment]
Fixed and published. Thanks for reporting it so quickly!
