### ISSUE TITLE
Compatibility with LOD mod Voxy

### ISSUE THREAD

**Issue by Taiyou06** [Qendolin/better-clouds#72]
There's this newly released mod LOD mod called [Voxy](https://modrinth.com/mod/voxy) and it's similar to DH and i love Better Clouds too so, adding support to it would be amazing!

**Comment by Qendolin** [comment]
That mod is closed source, so there's nothing I can do. Maybe if it gets more mature they'll release the source code.

**Comment by Taiyou06** [comment]
https://github.com/MCRcortex/voxy

source is now visible :p

**Comment by Qendolin** [comment]
I look at this again today and Voxy is still very much in the alpha stage. Once it's a little more stable someone can open a new issue.

**Comment by Qendolin** [comment]
Actually Voxy just works. You can use the mods together without issue. I just assumed there would be a problem, but there isn't.
