### ISSUE TITLE
Add cloud level/height setting

### ISSUE THREAD

**Issue by Fisch37** [Qendolin/better-clouds#73]
**Is your feature request related to a problem? Please describe.**
For my tastes the clouds render too low in the world. I don't like having my head stuck in the clouds on (comparatively) low heights.

**Describe the solution you'd like**
I'd like to have a setting for controlling the height clouds render in the world at. Some slider like I dunno "Cloud Level"

**Describe alternatives you've considered**
I looked around for some other mod on Modrinth that would allow me to change the setting. I am running this mod on Fabulously Optimized 1.20.2 with some added mods (nothing notable besides Nvidium) and I haven't seen any appropriate setting in the Sodium config either.

**Additional context**
See below a medium-sized mountain and the clouds hanging above it. I'd like to move those clouds further up
![Clouds above a mountain. Too low for my tastes](https://github.com/Qendolin/better-clouds/assets/46005543/ef43208c-3a0c-4173-b1ea-2d0855872c8c)

**Comment by Qendolin** [comment]
If you have Sodium Extras installed you can change the cloud height in the video settings. Additionally such an option already exist, I think in the "Generation" tab called "Offset" or something like that. If you know a better name please let me know.
