### ISSUE TITLE
Better Clouds Distant Horizon Visual Bug

### ISSUE THREAD

**Issue by Finsider** [Qendolin/better-clouds#74]
## Describe the bug
> A clear and concise description of what the bug is

whenever the player' screen looks towards the sky (or anywhere where clouds exists) there would be something getting in the way of the clouds, might be something related with DH since the issue doesn't exist when DH isn't enabled.

## To Reproduce
> Steps to reproduce the behavior

1. Download Distant Horizon, and Better Clouds (In my testing, 1.20.2)
2. Go to any world, (in my case, Wynncraft)
3. Wait until all the chunks are loaded
4. Try looking at the sky, if there isn't anything, try changing the LOD chunks distance whilst looking at buildings

### Expected behavior
> A clear and concise description of what you expected to happen.
1. Just a normal thing going on, no stuff happened in the image

### Screenshots
> If applicable, add screenshots to help explain your problem.
![2024-02-25_15 26 26](https://github.com/Qendolin/better-clouds/assets/91471471/45457c32-26e9-43cd-91b9-aec799082f2f)
![2024-0
![2024-02-25_15 32 04](https://github.com/Qendolin/better-clouds/assets/91471471/fa08d544-d340-4d13-bdbc-ba6b48273369)
2-25_15 26 32](https://github.com/Qendolin/better-clouds/assets/91471471/18280d05-3076-4f72-a92b-4cf79e6ac329)

### System Environment
- GPU: GTX 1070Ti
- Mod Version: 1.4.9 (DH 2.0.1-a - 1.20.2)
- OS: Windows 10

*Optional*
- Shader: 
- Other Mods: Distant Horizon

### Additional context
> Add any other context about the problem here.

**Comment by Finsider** [comment]
When we change the LOD distance, the thing we previously looked on, get stucked on the screen
![2024-02-25_15 41 12](https://github.com/Qendolin/better-clouds/assets/91471471/a82cb7b0-6bf1-48cc-9595-6e8b1ceaacfe)
![2024-02-25_15 41 15](https://github.com/Qendolin/better-clouds/assets/91471471/c1c7ab65-c301-4a01-bc4a-9766ba146b92)
![2024-02-25_15 41 31](https://github.com/Qendolin/better-clouds/assets/91471471/25e4ad75-6cec-483d-8f8b-e6c92604f79d)
there are cases where even I didn't change the distance, it get stucked, though I can't seem to reproduce them

**Comment by Qendolin** [comment]
Does reloading resources (F3+T) fix it temporarily?

**Comment by Finsider** [comment]
![2024-02-25_17 56 29](https://github.com/Qendolin/better-clouds/assets/91471471/8ab8cef9-4357-4d94-aee4-15fb0b770f70)
nope, it seems

**Comment by Finsider** [comment]
the bug can also be reproduced when 

1. enter a server
2. let the LOD to load first
3. /hub 
4. go back to the current world

**Comment by Qendolin** [comment]
I've traced this back to an oversight in DH's code. I'll ask on their DC and a fix should be ready within the next few days.

**Comment by Qendolin** [comment]
I've conversed with the DH dev and a (temporary) fix will be in the next update of Better Clouds.

**Comment by BORTlort** [comment]
Will the update fix this problem on the 1.20.1 version as well?

**Comment by Qendolin** [comment]
Yes. Sorry that it's taking so long, I'm busy.

**Comment by Qendolin** [comment]
I think this issue has been resolved. Correct me if I'm wrong
