### ISSUE TITLE
distant clouds get hidden depending on viewing angle 

### ISSUE THREAD

**Issue by 1ETHeR-1** [Qendolin/better-clouds#75]
## Describe the bug
> A clear and concise description of what the bug is

Distant clouds get cut off at certain vertical viewing angles.

## To Reproduce
> Steps to reproduce the behavior

1. Increase cloud size and density, and "Scale Falloff" for better viewing. 
2. Set "Height Offset" to max, stand near sea level.
3. Set "Distance" to max.
4. Set render distance to 10 or below. The lower, the less subtle the effect.
5. Cast your gaze towards the heavens.
6. Move mouse so that the furthest clouds are positioned at the top of the screen, then look down so they're at the bottom; repeat.
7. When clouds are hidden turn view left and right to hide other clouds.

### Expected behavior
> A clear and concise description of what you expected to happen.

Clouds remain visible no matter their location on the screen if not behind blocks.

### Screenshots
> If applicable, add screenshots to help explain your problem.

Here is an [imgur link](https://imgur.com/a/JPse2Zn) with mp4's, as it's easier to see in motion.

![2024-02-26_02 29 36](https://github.com/Qendolin/better-clouds/assets/16327424/72220766-3510-407f-9150-ba8e8a8c3ec1)
![2024-02-26_02 29 33](https://github.com/Qendolin/better-clouds/assets/16327424/8cb7c10d-392e-446c-baa1-50ede77e0f96)
![2024-02-26_02 29 30](https://github.com/Qendolin/better-clouds/assets/16327424/4e4e3122-4ad4-4f5a-9218-924cd6b873ec)
![Untitled](https://github.com/Qendolin/better-clouds/assets/16327424/9584c812-9d42-4377-b8a2-e95e746b0380)

### System Environment
- GPU: GeForce GTX 1080
- Mod Version: 1.3.16
- OS: Windows 10

*Optional*
- Other Mods: Sodium, Sodium Extra. Tested with no other mods installed, same results.

### Additional context
> Add any other context about the problem here.

How much the effect happens depends on a combination of what your render distance is, how high up clouds are from you, and what "distance" is set to.
Stacking a lower render distance, a high height offset, and a high "cloud height" from sodium makes clouds almost always hidden.

**Comment by Qendolin** [comment]
I've looked at the issue and it happens because I don't take y-distance into consideration. The real fix would also reduce the visible range in cases where it's not needed. So I'm choosing a different solution where I just make the cutoff more gradual.

**Comment by Qendolin** [comment]
This is fixed, tho it can still happen in very specific cases.
