### ISSUE TITLE
cannot get mod to work

### ISSUE THREAD

**Issue by Guma43** [Qendolin/better-clouds#78]
whenever i put this mod into my mods folder i cannot open minecraft without it a can easily, im not sure what the problem
![error](https://github.com/Qendolin/better-clouds/assets/163459518/26264ba2-2ffe-4515-9771-8fd6a22714b2)

**Comment by Qendolin** [comment]
Which mod version / mc version are you using?
Anyway, you need to use at least java 17. You are using java 16.
Preemptively: No I can't tell you how to change it.

**Comment by Qendolin** [comment]
Closing due to no response
