### ISSUE TITLE
Visual Error in Cloud Rendering

### ISSUE THREAD

**Issue by Weskerson** [Qendolin/better-clouds#79]
I've been trying to figure out a cause for this error as it's been working fine in my game up till one day when I noticed that the clouds have this weird rendering error that can't seem to be fixed. I've tried updating all my drivers, done a fresh install of minecraft, but nothing seems to work. Taking a screenshot with the high quality screenshot mod seems to show a perfectly working mod, but taking the screenshot with the windows clip tool shows what I see. I've also tried to play around with different mod versions for both 1.20.1 and 1.20.4 but both versions produce the same glitch. I have quite a few mods as well so I did take the liberty of testing the mod on its own and still get the same results so it's definitely not a mod conflict.

- GPU: AMD Radeon Graphics
- Mod Version: 1.3.16 for 1.20.1
- OS: Windows 11

[2024-04-01-5.log](https://github.com/Qendolin/better-clouds/files/14835409/2024-04-01-5.log)
![huge_2024-04-01_22 08 25](https://github.com/Qendolin/better-clouds/assets/88669403/d9ad6630-a7e4-4502-a560-8a3a766987a6)
With the screenshot mod
![Screenshot 2024-04-01 220859](https://github.com/Qendolin/better-clouds/assets/88669403/507504da-e625-40c4-85f6-1f29cd8d6342)
With windows screenshot tool (What I see)

**Comment by Qendolin** [comment]
Does the issue also happen when only Better Clouds and it's dependencies are loaded?

**Comment by Weskerson** [comment]
> Does the issue also happen when only Better Clouds and it's dependencies are loaded?

Yeah, made a fresh install to test it out too, does the exact thing on 1.20.1 and 1.20.4 so Im unsure if it's a pc thing or a mod thing.

**Comment by Qendolin** [comment]
To me it looks like a driver issue. Can you send a screenshot of your F3 screen?

**Comment by Weskerson** [comment]
![Screenshot 2024-04-03 120641](https://github.com/Qendolin/better-clouds/assets/88669403/2c3193f9-7d16-4320-abe5-eaf429249e79)
