### ISSUE TITLE
Feature: Color/opacity adjustments for time of day and weather

### ISSUE THREAD

**Issue by BryceBubbles** [Qendolin/better-clouds#8]
Having some control over the colour and opacity of the clouds for different times of day and weather events would be next level!

I can see that being quite difficult to implement though, so some hard coded tweaks would be my next thought:

- The clouds look quite blue at night, could they be desaturated more towards white?
- During rain and thunder could they turn dark grey? At the moment if opacity is low they sort of disappear.
- During sunrise and sunset they look awesome towards the sun, but it would be cool if the clouds away from the sun caught some of the colour.
- The clouds look amazing during a clear day, so no issues there :)

**Comment by Qendolin** [comment]
I want that too but it's not straight forward and I haven't had the time to think of a good solution but if I do I'm def. gonna add this

**Comment by Qendolin** [comment]
The newest beta release features a bunch of new options, improved lighting and seperate settings for day and night brightness. From my testing these new options suffice to cutomize the look to my liking. I'ld appreciate if you could check out the new version and give me some feedback regarding the color options.

**Comment by Qendolin** [comment]
I consider this done
