### ISSUE TITLE
Compatibility with Head in the Clouds (Sunshine above the clouds)

### ISSUE THREAD

**Issue by HB-Stratos** [Qendolin/better-clouds#81]
### Is your feature request related to a problem? Please describe.
I recently tested Head in the Clouds ( https://modrinth.com/mod/head-in-the-clouds ), a mod that makes the sun shine when above the clouds. I love the effect when flying through the clouds from under the rain. However, from above the effect looks very weird and the illusion is quickly broken as one can see clearly below the clouds where there previously was dark fog. This is especially impacted as cloud density above the clouds reduces to sunny day levels even if there is a thunderstorm underneath. 

https://github.com/Qendolin/better-clouds/assets/56313836/4b73ea27-f6f2-46d6-9b26-e1e5de6e7297

### Describe the solution you'd like
I think it might work if Better Clouds was able to recognize that the weather was set to rain / thunder even if the world is currently showing sunlight above the clouds. If this state was recognized the cloud density below the player should match the density the player would be seeing from underneath in the bad weather. This should help to mask the effect of suddenly having good weather below the clouds when above them. 
Cloud Density from below:
![image](https://github.com/Qendolin/better-clouds/assets/56313836/d37935bb-5afa-4dd7-a3fb-87f47c0b2556)
Cloud Density from above:
![2024-04-22_23 05 02](https://github.com/Qendolin/better-clouds/assets/56313836/460271a3-e238-486a-b968-b031c7b7588a)
These two densities should ideally match to mask the effect of rain not rendering under clouds. 
### Describe alternatives you've considered
I haven't been able to come up with any

### Additional context
https://github.com/Qendolin/better-clouds/issues/59 I found this and see that some level of compatibility was already added, presumably to make the weather change work at all based on height. 
I believe my issue here still remains valid as it is an additional enhancement on top of this.

**Comment by Qendolin** [comment]
While this is valid issue, there is not much that I can do. The Head In the Clouds mod simply sets the weather to sunny when above the clouds. There is not really a way for me to detect that it should still be dense, rain clouds underneath. Unless HITC adds an api for mod compatibility I really can't do much else.

**Comment by HB-Stratos** [comment]
> While this is valid issue, there is not much that I can do. The Head In the Clouds mod simply sets the weather to sunny when above the clouds. There is not really a way for me to detect that it should still be dense, rain clouds underneath. Unless HITC adds an api for mod compatibility I really can't do much else.

DaFuqs has replied to my issue over there, communicating that they will add such an API. So this may just work.

**Comment by DaFuqs** [comment]
I added a small API package via https://github.com/DaFuqs/HeadInTheClouds/commit/9ed121462ee0e46fe4a3e3d2cc57b488bc4de128 for mc 1.20.1-1.20.6.
If you need anything lmk

**Comment by Qendolin** [comment]
Guys, have I already fixed this issue?

**Comment by SabrCat** [comment]
> Guys, have I already fixed this issue?

I haven't tested recently, but seeing as there are no commits mentioning it since the API was added to HeadInTheClouds, this feature is most likely not implemented yet.

**Comment by Qendolin** [comment]
Yes but I think I've implemented a workaround before the API was done. There is also some code for it. I guess I should just try it out.

**Comment by Qendolin** [comment]
Yup, just tested it out in the 1.21 version and everything works perfectly. This should be working for 1.20.1 onwards.

**Comment by bravely-beep** [comment]
~~My current setup involves running NeoForge 1.21.1, with Better Clouds `v1.13.5-beta+1.21.1` installed as a native NeoForge version, and Head in the Clouds `1.1.0` installed via Sinytra Connector. The compatibility features for these two mods don't seem to work with this setup.~~

~~Would it be feasible to look at fixing this? Or is this just unsupported?~~

EDIT: ignore me, made a mistake in my testing. This works correctly.

**Comment by Qendolin** [comment]
You could try running the fabric version of BC via synitra
