### ISSUE TITLE
Minecraft crashes when I try to open Better Clouds settings using ModMenu, even if i am in menu

### ISSUE THREAD

**Issue by Romazess** [Qendolin/better-clouds#83]
## Description
after clicking on the settings, i see "saving the world" for few seconds, then mc crahes 
in game everything works fine
### System Environment
- GPU: 6650xt
- Mod Version: 1.3.16 1.20.1
- OS: win10 pro 64

*Optional:*
- Shader Pack: -
- Other Mods: a lot

### Game Log / Crash Report
[crash-2024-04-25_20.10.26-client.txt](https://github.com/Qendolin/better-clouds/files/15108691/crash-2024-04-25_20.10.26-client.txt)

**Comment by Qendolin** [comment]
For a temporary fix you could try using yacl 3.3, I think that should work

**Comment by Romazess** [comment]
that helped, thanks

**Comment by humscode** [comment]
> For a temporary fix you could try using yacl 3.3, I think that should work

i tried finding yacl 3.3 for 1.20.1 but i couldnt find it, help please

**Comment by humscode** [comment]
> > For a temporary fix you could try using yacl 3.3, I think that should work
> 
> i tried finding yacl 3.3 for 1.20.1 but i couldnt find it, help please

Using YACL 3.2.2+1.20 (Fabric) works and fixes this issue for minecraft 1.20.1
