### ISSUE TITLE
The game crashes when starting in version 1.20.5

### ISSUE THREAD

**Issue by J4PC** [Qendolin/better-clouds#85]
## Description
> The game crashes when you start it.

### System Environment
- GPU: RTX 3080
- Mod Version: better-clouds-1.5.7+1.20.4
- OS: Windows 11

- Shader Pack: -
- Other Mods: 
  - fabric-api-0.97.6+1.20.5
  - YetAnotherConfigLib-3.4.1+1.20.5-fabric

### Game Log / Crash Report
[crash-2024-04-26_15.09.32-client.txt](https://github.com/Qendolin/better-clouds/files/15131054/crash-2024-04-26_15.09.32-client.txt)

**Comment by Qendolin** [comment]
https://modrinth.com/mod/better-clouds/version/1.6.0+1.20.6-b
