### ISSUE TITLE
Game crashes as the settings are opened "java.lang.NoSuchFieldError: tabNavigationBar"

### ISSUE THREAD

**Issue by MaciejMocarski** [Qendolin/better-clouds#86]
## Description
> The whole game crashes, as the settings of clouds are being opened, probably due to wrong naming of the variables or there is a specific way to open better clouds' settings that i do not see

### System Environment
- GPU: GeForce RTX 3060
- Mod 1.5.7+1.20.4-R
- OS: Windows 11

*Optional:*
- Shader Pack: None
- Other Mods: uhhhh, a lot but this is the only one that messes with the clouds or skyboxes

### Game Log / Crash Report
[crash.txt](https://github.com/Qendolin/better-clouds/files/15140371/crash.txt)

**Comment by Qendolin** [comment]
Should be fixed for 1.20.4 & 1.20.1:
https://modrinth.com/mod/better-clouds/version/1.5.8+1.20.4-R  
https://modrinth.com/mod/better-clouds/version/1.3.17+1.20.1-R
