### ISSUE TITLE
Incompatible with YetAnotherConfigLib version 3.4.0 and up

### ISSUE THREAD

**Issue by Carl-Kabat** [Qendolin/better-clouds#88]
When trying to open config screen, game crashes.
Last compatible YACL version: 3.3.2

**Comment by Qendolin** [comment]
Should be fixed for 1.20.4 & 1.20.1:
https://modrinth.com/mod/better-clouds/version/1.5.8+1.20.4-R  
https://modrinth.com/mod/better-clouds/version/1.3.17+1.20.1-R
