### ISSUE TITLE
Incompatibility with Fog Looks Good Now (Fabric)

### ISSUE THREAD

**Issue by deathwing1423** [Qendolin/better-clouds#89]
Default settings of Fog Looks Good Now (Fabric) cause visual issues with Better Clouds. When you reduce fog visibility to 100% from the default 120% the issue ends.

Default settings.
![2024-05-02_10 35 10](https://github.com/Qendolin/better-clouds/assets/136675132/009ab115-9607-49df-b150-20fa3dc10cf1)

Reduce fog visibility to 100%
![2024-05-02_10 35 28](https://github.com/Qendolin/better-clouds/assets/136675132/8fa7c67d-47f2-4ca4-ad4e-e179978f3f94)

**Comment by Qendolin** [comment]
Mineblock11 is currently completely rewriting and rebranding the mod. I'll probably add compat once it's done.

**Comment by Qendolin** [comment]
The successor to FLGN is now released: https://modrinth.com/mod/fog someone can open a new issue now if it's still desired
