### ISSUE TITLE
1.20.6 Compatibility

### ISSUE THREAD

**Issue by DeadLector** [Qendolin/better-clouds#94]
**Is your feature request related to a problem? Please describe.**
I'd love to use this mod on Minecraft 1.20.6.

**Describe the solution you'd like**
An compatibility update to 1.20.6.

**Describe alternatives you've considered**
I haven't found any I like personally.

**Additional context**
No additional context needed.

**Comment by Qendolin** [comment]
CC #85

**Comment by Qendolin** [comment]
I have started working on the update, and I got it running, but currently no clouds are visible. I haven't had time to look into the issue any further and I cannot give an estimate when it will be ready. Could be in the next few days, or not.

**Comment by DeadLector** [comment]
Sorry didn't see that one! I'm happy you're just looking into it! Take your time!

Thank you in advance!

**Comment by Qendolin** [comment]
https://modrinth.com/mod/better-clouds/version/1.6.0+1.20.6-b 
I haven't fully tested it
