### ISSUE TITLE
Clouds flickering with Nausea potion effect

### ISSUE THREAD

**Issue by Matz-42** [Qendolin/better-clouds#96]
Clouds flickers in and out of existence while under the Nausea Potion effect.

- GPU: NVIDIA GeForce GTX 1650
- Mod Version: 1.6.0 beta
- OS: Windows 11
- Other Mods: Fabric API 0.97.8; Yet Another Config Lib 3.4.2

**Comment by Qendolin** [comment]
Should be fixed: https://modrinth.com/mod/better-clouds/version/1.7.0+1.21-b

**Comment by Qendolin** [comment]
Please comment if this issue still occurs
