### ISSUE TITLE
Nvidium incompatibility: Clouds flickering with view bobbing

### ISSUE THREAD

**Issue by Matz-42** [Qendolin/better-clouds#97]
Clouds flickers in and out of existence while walking with view bobbing on.
I was able to isolate the problem to Nvidium, removing it resolved the problem.

- GPU: NVIDIA GeForce GTX 1650
- Mod Version: 1.6.0 beta
- OS: Windows 11
- Other Mods: Fabric API 0.97.8; Yet Another Config Lib 3.4.2; Sodium 0.5.8; **Nvidium 0.2.7**

This seems similar enough to #96 that I suspect that there is the same underlying problem underneath, unsure why this one only happens with Nvidium though.

**Comment by Qendolin** [comment]
Should be fixed https://modrinth.com/mod/better-clouds/version/1.7.0+1.21-b

**Comment by Qendolin** [comment]
Please comment if this issue still occurs
