### ISSUE TITLE
Clouds flickering with view bobbing and a higher than vanilla render distance (>41 chunks)

### ISSUE THREAD

**Issue by Matz-42** [Qendolin/better-clouds#98]
Clouds flickers in and out of existence while walking with view bobbing on and a higher than vanilla render distance. From testing this only seems to happen at 42 chunks or above. Tested with both C2ME and Bobby alternatively.

- GPU: NVIDIA GeForce GTX 1650
- Mod Version: 1.6.0 beta
- OS: Windows 11
- Other Mods: Fabric API 0.97.8; Yet Another Config Lib 3.4.2; C2ME 0.2.0+alpha.11.95
- Other Mods (alternative): Fabric API 0.97.8; Yet Another Config Lib 3.4.2; Bobby 5.2.0

Probably related to #97

**Comment by Qendolin** [comment]
Should be fixed: https://modrinth.com/mod/better-clouds/version/1.7.0+1.21-b

**Comment by Qendolin** [comment]
Please comment if this issue still occurs
