### ISSUE TITLE
Crash on start-up

### ISSUE THREAD

**Issue by DrFurnace** [Qendolin/better-clouds#99]
im trying to use the1.20.4 verison but everytime i tried to open mc it says its incompatible

**Comment by Qendolin** [comment]
I really can't help you if you don't attach your game log (latest.log). If you don't know where to find it, google can help you.

**Comment by DrFurnace** [comment]
ok thanks :)

**Comment by Qendolin** [comment]
So are you not going to upload the log?

**Comment by DrFurnace** [comment]
Sorry I’ve been distracted with finals cause they are today I can send them around 4:30 PM (EST)

**Comment by DrFurnace** [comment]
![bd89fda806a378f195fdb6d016cc0d1f70e603b1](https://github.com/Qendolin/better-clouds/assets/169957385/6a4f232f-f4ed-4f7a-8849-0f51bea22779)

**Comment by DrFurnace** [comment]
Sorry wrong image (I’m new to this a my computer never wants to show the things I need) I’ll get it for you a few minutes while I try to get the image to work

**Comment by DrFurnace** [comment]
this good?
![log5162024](https://github.com/Qendolin/better-clouds/assets/169957385/cd1539bc-f160-436f-9700-c0a4d776dfd3)

**Comment by Qendolin** [comment]
You also need to install https://modrinth.com/mod/yacl/version/3.4.2+1.20.4-fabric, it's a required dependency

**Comment by DrFurnace** [comment]
ive been messing with mods on java and i guess I havent fully figured things out lol. Thank you so much this mod will match perfectly with my other ones.
